export const TR = {
    Translator: "Çeviren",
    TranslatorName: "Readrift(Ege Kaymaz)",
    Language: "Dil",
    ThisLanguage: "Türkçe",
    OK: "Tamam",
    SteelMill: "Çelik fabrikası",
    StainlessSteelPlant: "Paslanmaz Çelik Fabrikası",
    CircuitFoundry: "Devre Dökümhanesi",
    IntegratedCircuit: "Entegre Devre",
    OilWell: "Petrol Kuyusu",
    Wood: "Odun",
    LoggingCamp: "Odun Üretimhanesi",
    LumberMill: "Kereste fabrikası",
    Lumber: "Kereste",
    Paper: "Kağıt",
    PaperMill: "Kağıt fabrikası",
    Book: "Kitap",
    BookPublisher: "Kitap yayınlayayıcısı",
    OilRefinery: "Yağ Rafinerisi",
    Sell: "Sat",
    Upgrade: "Yükselt",
    Build: "İnşa et",
    Buildings: "Yapılar",
    Iron: "Demir",
    FuelType: "Yakıt türü seç",
    FuelCost: "Yakıt maliyeti",
    FuelEconomy: "Yakıt ekonomisi",
    FuelInStorage: "%{fuel} Depoda",
    Plastic: "Plastik",
    Petrol: "Petrol",
    Buy: "Sat",
    Multiplier: "Katlayıcı",
    MultiplierDesc: "Her 10 seviyede bir +1 çarpanı alırsınız ",
    SellBuilding: "Yapıyı sat",
    PowerGrid: "Güç ızgarası",
    SortBy: "Göre sırala",
    SortByPrice: "Fiyat",
    SortByAmount: "Miktar",
    NotEnoughResources: "Bu işlem için yeterli kaynak(lar) yok",
    Transportation: "Taşıma",
    Cash: "Para",
    Aluminum: "Alüminyum",
    ResearchPoint: "Araştırma Puanı",
    Unlock: "Araştır",
    BuildingUnlocked: "%{building} ın kilidi açıldı ",
    Science: "Bilim",
    ScienceFromPowerDesc: "Enerji santralleri, güç üretirken az miktarda Bilim üretir",
    Culture: "Kültür",
    School: "Okul",
    University: "Üniverste",
    Polytechnic: "Politeknik",
    Colosseum: "Kolezyum",
    WindTurbine: "Rüzgar türbini",
    Engine: "Motor",
    EngineFactory: "Motor Fabrikası",
    CameraFactory: "Kamera Fabrikası",
    Camera: "Kamera",
    Gun: "Silah",
    GunFactory: "Silah fabrikası",
    Aircraft: "Uçak",
    AircraftFactory: "Uçak fabrikası",
    Zeppelin: "Zeplin",
    ZeppelinFactory: "Zeplin Fabrikası",
    Tank: "Tank",
    TankFactory: "Tank Fabrikası",
    CoalPowerPlant: "Kömürlü Termik Santral",
    PetrolPowerPlant: "Petrol Güç Santrali",
    Copper: "Bakır",
    Gas: "Doğalgaz",
    GasPump: "Doğalgaz Pompası",
    GasPowerPlant: "Doğalgaz Santrali",
    Missile: "Füze",
    MissileFactory: "Füze Fabrikası",
    Rocket: "Roket",
    RocketFactory: "Roket Fabrikası",
    BuildingPermit: "Yapı izini",
    BuildingPermitDesc: "%{amount} binalar için izininiz var, ama %{amountBuilt} oluşturdunuz ve %{amountLeft} kaldı",
    BuildingLocked: "Bina henüz mevcut değil, önce araştırma laboratuarında kilidini açmanız gerekir ",
    MaxBuilders: "Maksimum İnşaat",
    MaxBuildersDesc: "Aynı anda inşa edebileceğiniz bina sayısı",
    Silicon: "Silikon",
    AluminumMine: "Alimünyum Madeni",
    CopperMine: "Bakır Madeni",
    SiliconMine: "Silikon Madeni",
    IronMine: "Demir Madeni",
    CoalMine: "Kömür madeni",
    Headquarter: "Merkez",
    ResearchLab: "Araştırma Laboratuvarı",
    TradeCenter: "Pazar Yeri",
    Resources: "Kaynaklar",
    NotEnoughCash: "Bu işlem için yeterli nakit yok",
    NotEnoughSwissMoney: "Bu operasyon için yeterli Swiss parası yok",
    BuildingNotEnoughFuel: "💡 Yeterli değil %{fuel}",
    AutoSell: "Otomatik Sat",
    Change: "Değiştir",
    StatisticsBureau: "İstatistik Bürosu",
    LogisticsDepartment: "Lojistik Departmanı",
    From: "İtibaren",
    Top20FuelCost: "İlk 20 Yakıt Maliyeti",
    To: "İle",
    TransportTime: "Transfer Zamanı",
    Warehouse: "Depo",
    TradeWarehouse: "Nakliye Deposu",
    Coal: "Kömür",
    Video: "Video",
    ClothingFactory: "Giysi Fabrikası",
    Clothes: "Giysi",
    Fashion: "Moda",
    FashionFactory: "Moda Fabrikası",
    VideoFarm: "Video Çiftliği",
    SantaFactory: "Noel Baba Fabrikası",
    Santa: "Noel Baba",
    Car: "Araba",
    CarFactory: "Araba Fabrikası",
    Ship: "Gemi",
    SolarPanel: "Güneş Paneli",
    SolarPanelDesc: "💡 Güneş Panelleri her 10 saniyede sadece 5 saniye çalışır - tüm döngüler hizalıdır",
    WindTurbineDesc: "💡 Rüzgar Türbinleri her 10 saniyede yalnızca 8 saniye çalışır - döngüler hizalı değildir",
    Movie: "Film",
    MovieStudio: "Film Stüdyosu",
    Sitcom: "Komedi Filmi",
    TVStudio: "TV Stüdyosu",
    PC: "Bilgisayar",
    GameStudio: "Oyun Stüdyosu",
    Game: "Oyun",
    ComputerFactory: "Bilgisayar Fabrikası",
    Shipyard: "Tershane",
    PowerUsage: "Güç Kullanımı",
    PowerSupply: "Güç Kaynağı",
    Level: "Seviye",
    Power: "Güç",
    CentralBank: "Merkez Bankası",
    ResourceInput: "Üretim",
    ResourceOutput: "Tüketim",
    ResourceStorage: "Depo",
    ResourceChange: "Değişimi",
    ResourceInOutDesc:
        "💡 Karşılık gelen çıkış ve giriş binalarını vurgulamak için yukarıdaki Giriş-Çıkış sayılarına dokunun",
    MarketUpdateIn: "%{time} içinde bir sonraki piyasa fiyatı güncellemesi",
    Semiconductor: "Çip",
    SemiconductorFactory: "Çip Fabrikası",
    Steel: "Çelik",
    Bitcoin: "Bitcoin",
    BitcoinFarm: "Bitcoin Madeni",
    Dogecoin: "Dogecoin",
    DogecoinFarm: "Dogecoin Madeni",
    Guitar: "Gitar",
    GuitarFactory: "Gitar Fabrikası",
    Drum: "Davul",
    DrumFactory: "Davul Fabrikası",
    RecordingStudio: "Kayıt Stüdyosu",
    OperaHouse: "Opera binası",
    CoalGasificationPlant: "Kömür Gazlaştırma Tesisi",
    GasProcessingPlant: "Gaz İşleme Tesisi",
    Music: "Müzik",
    Glass: "Cam",
    PhoneFactory: "Telefon Fabrikası",
    Phone: "Telefon",
    GlassFactory: "Cam Fabrikası",
    Oil: "Yağ",
    Chromium: "Krom",
    ChromiumMine: "Krom Madeni",
    Uranium: "Uranyum",
    EnrichedUranium: "Zenginleştirilmiş Uranyum",
    NuclearPowerPlant: "Nükleer Güç Santrali",
    UraniumEnrichmentPlant: "Uranyum Zenginleştirme Tesisi",
    UraniumMine: "Uranyum Madeni",
    Titanium: "Titanyum",
    TitaniumMine: "Titanyum Madeni",
    TitaniumAlloyPlant: "Titanyum Alaşım Tesisi",
    ChromiumAlloyPlant: "Krom Alaşım Tesisi",
    Input: "Üretim",
    PanelPosition: "Panel Pozisyonu",
    Output: "Output",
    OutputCapacity: "Tüketim Kapasitesi",
    ResourceDeposit: "Kaynak Yatırımı",
    AdjacentBonus: "Bitişik Bonusu",
    AdjacentBonusDesc: "Aynı türdeki her bitişik çalışan bina için %{bonus}% ekstra kapasite elde edersiniz",
    ConsiderIncreaseProduction: "💡 %{resource} üretimini artırmayı düşünün",
    ProductionCycleLength: "Üretim Döngüsü",
    ProductionCycleLengthDesc:
        "Saniye cinsinden ölçülen bir üretim döngüsünün süresi. Döngünün uzatılması, döngü başına girdi/çıktıyı buna göre artıracak ve böylece girdi kaynaklarını alırken önceliğini azaltacaktır.",
    MaxInputDistance: "Maksimum Girdi Mesafesi",
    MaxInputDistanceDesc:
        "Bu binanın girdi kaynaklarını getirebileceği maksimum mesafe, karo sayısıyla ölçülür",
    AutoSellConcurrency: "Eş Zamanlı Otomatik Satış",
    AutoSellConcurrencyDesc: "Otomatik satışın aynı anda işleyebileceği maksimum kaynak sayısı",
    MaxAutoSellConcurrencyReached:
        "Maksimum eşzamanlı otomatik satış sınırına ulaştınız, bunu etkinleştirmek için başka bir otomatik satışı kapatın",
    WallStreet: "Borsa Merkezi",
    MarketCap: "Piyasa Değeri",
    MarketCapDesc: "Şirketinizin toplam piyasa değeri",
    BuildingValuation: "Bina Değeri",
    BuildingValuationDesc: "Bina izinleri ve iyileştirmeler dahil olmak üzere binalarınızın toplam değeri",
    ResourcesValuation: "Kaynak Değeri",
    ResourcesValuationDesc: "Envanterinizdeki kaynakların toplam değeri",
    Battery: "Batarya",
    BatteryFactory: "Batarya Fabrikası",
    RatingBuy: "Satın Al",
    RatingSell: "Sat",
    SwissShop: "Swiss Marketi",
    RatingHold: "Tut",
    RatingOutperform: "Daha iyi performans",
    RatingUnderperform: "Düşük performans",
    StockRating: "Fon Değeri",
    JetEngine: "Jet Motoru",
    Helicopter: "Helikopter",
    Lithium: "Lityum",
    LithiumMine: "Lityum Madeni",
    LiionBatteryFactory: "Li-ion Batarya Fabrikası",
    HelicopterFactory: "Helikopter Fabrikası",
    Satellite: "Uydu",
    ToyFactory: "Oyuncak Fabrikası",
    Toy: "Oyuncak",
    SpaceStation: "Uzay İstasyonu",
    SpaceStationFactory: "Uzay İstasyon Fabrikası",
    OperatingSystem: "İşletim Sistemi",
    OperatingSystemCompany: "İşletim Sistem Şirketi",
    LinuxDistribution: "Linux Dağıtımı",
    Internet: "İnternet",
    WebBrowser: "İnternet Tarayıcısı",
    Console: "Konsol",
    ConsoleFactory: "Konsol Fabrikası",
    Train: "Tren",
    TrainFactory: "Tren Fabrikası",
    ShoeFactory: "Ayakkabı Fabrikası",
    Shoes: "Ayakkabı",
    ArtilleryFactory: "Ağırsilah Fabrikası",
    Artillery: "Ağırsilah",
    SubmarineFactory: "Denizaltı Fabrikası",
    Submarine: "Deniz Altı",
    Spaceship: "Uzay Gemisi",
    RobotFactory: "Robot Fabrikası",
    Robot: "Robot",
    SpaceshipFactory: "Uzaygemisi Fabrikası",
    SatelliteFactory: "Uydu Fabrikası",
    JetEngineFactory: "Jet Motor Fabrikası",
    StockRatingDesc:
        "Wall Street analistlerinden pazar değerinizi etkileyen ve pazarla birlikte güncellenen hisse senedi derecelendirmesi",
    OfflineEarning: "Çevrimdışı Kazanç",
    PerMin: "%{amount}/dakika",
    OfflineEarningTime: "Çevrimdışı Kazanç Süresi",
    OfflineEarningTimeDesc: "Bu eşiğe kadar çevrimdışı kazanç elde edeceksiniz",
    BuyPermit: "İzin Satın Al",
    Settings: "Ayarlar",
    Sound: "Ses Efekti",
    SoundDesc: "Tıklama veya hata sesi gibi ses efektlerini açın",
    MusicDesc: "Müziği Aç: It's Not Over 'Til The Bossa Nova by Shane Ivers (https://www.silvermansound.com)",
    Credits: "Krediler",
    Icons: "İkonlar",
    MisplacedBuilding: "⛔ Bu %{building}, doğru kaynak deposunun üstüne yerleştirilmemiş",
    HighlightBuildings: "Binaları Vurgula",
    HighlightTurnedOff: "...kapatılanlar",
    HighlightStockpileModeOn: "...stok modu açık olan",
    HighlightProductionCycleNotDefault: "...üretim döngüsüne sahip olan > 1",
    HighlightMaxInputDistanceNotDefault: "...maksimum girdi mesafesine sahip < ∞",
    HighlightNotMakingProfit: "...kar etmeyen",
    NBuildingsAreHighlighted: "%{n} bina(lar) vurgulanmıştır",
    TurnOffProduction: "Üretimi Durdur",
    TurnOffProductionDesc:
        "Binanın üretimini kapatın. Bina artık kaynakları taşımayacak ve güç kullanmayacak",
    FuelCostNumber: "%{cost} %{fuel}",
    Unlimited: "Sınırsız",
    Transport: "Ulaşım",
    TileModifier: "Karo bonusu",
    ShowAllModifiers: "Bütün bonusları Göster",
    HideAllModifiers: "Bütün bonusları Gizle",
    NumberOfBuildings: "Bu kadar binan var:",
    ShowContent: "İçerikleri göster",
    HideContent: "içerikleri gizle",
    BuyExpansionPack: "%{price} Kadar fiyat al",
    Cities: "Şehirler",
    InputStrategy: "İçeri Alma Stratejisi",
    InputStrategyClose: "Yakın",
    InputStrategyCloseDesc: "Yeterli kaynağa sahip en yakın depoyu tercih edin",
    InputStrategyFar: "Uzak",
    InputStrategyFarDesc: "Yeterli kaynağa sahip en uzak depoyu tercih edin",
    InputStrategyAmount: "Miktar",
    InputStrategyAmountDesc: "Mesafeden bağımsız olarak kaynakların en fazla olduğu depoyu tercih edin",
    FuelCostSave: "Yakıt Maliyetinden Tasarruf",
    FuelCostSaveDescV2:
        "Depolar, diğer binalara kıyasla kaynakların taşınması için belirli bir oranda yakıt tasarrufu sağlar, seviye ne kadar yüksekse, tasarruf o kadar fazla olur",
    SoftwareCompany: "Yazılım Şirketi",
    Software: "Yazılım",
    ScreenFactory: "Ekran Fabrikası",
    Screen: "Ekran",
    JoinDiscord: "Yeni güncellemeler, ipuçları ve tartışmalar için Discord sunucumuza katılın",
    ClaimOfflineEarning: "Çevrimdışı Ödülünü Topla",
    OfflineTime: "Çevrimdışı zamanı",
    Minutes: "%{time} dakika",
    MaxUpgrade: "Maksimum Geliştirme",
    MaxUpgradeDesc: "Maksimum geliştirmeye ulaştınız",
    ClaimAmount: "Nakit +%{amount}",
    EffectiveTime: "Etkin Zaman",
    EffectiveTimeDesc: "Etkin çevrimdışı kazanma süreniz %{time}dk ile sınırlıdır.",
    BuildSearchPlaceholder: "Aramak için bina veya kaynak yazın",
    MineOverlayWarning: "%{building}, karo bonusundan etkilenmez",
    WholesaleCenter: "Toptan Satış Merkezi",
    OrderFrom: "%{name}'dan sipariş ver",
    ExpireIn: "Son Kullanma Tarihi",
    Reward: "Bedel",
    PerSecond: "%{time}/saniye",
    PolicyPoint: "Politika Puanı",
    PolicyPointDesc: "💡 Daha çok politika aktif etmek, her bir politika için daha fazla maliyet demektir.",
    NextOrderIn: "Sıradaki Sipariş",
    FillOrder: "Siparişi gönder",
    RejectOrder: "İptal et",
    WholesaleCenterLocked:
        "Toptan Satış Merkezi'nin kilidini açmak için en az %{required} farklı kaynağa ihtiyacınız var. Yalnızca %{current} kaynağınız var",
    OrderFilled: "%{from} siparişi başarıyla dolduruldu!",
    PolicyCenter: "Politika Merkezi",
    NewOrder: "%{from}'dan yeni bir sipariş geldi, lütfen Toptan Satış Merkezi'ne göz atın",
    Policies: "Politikalar",
    PolicyNotEnoughTime: "Bu politika için yeterli politika puanınız yok",
    WholesaleCenterOrderFasterDesc: "Toptan Satış Merkezi siparişleri 2x daha hızlı alıyor ve sipariş boyutu 2x daha büyük",
    PolicyOilWellPowerx2: "Petrol Kuyusunu Güçlendirin",
    PolicyOilWellPowerx2Desc: "Petrol kuyuları 2x petrol üretir ve 2x güç kullanır",
    HalfTransportSpeed: "Tasarruf Etmek İçin Yavaşlayın",
    HalfTransportSpeedDesc: "Ulaşım hızı %25 yavaşlar ve yakıt maliyeti %25 azalır",
    RefineryMoreOil: "Çok Petrol Az Plastik",
    RefineryMoreOilDesc: "Petrol Rafinerileri %50 daha fazla petrol ve %50 daha az plastik üretiyor",
    RefineryMorePlastic: "Az Petrol Çok Plastik",
    RefineryMorePlasticDesc: "Petrol Rafinerileri %50 daha az petrol ve %50 daha fazla plastik üretiyor",
    FreeOilTransportDesc: "Petrol taşımacılığı yakıta mal olmaz, ancak petrol kuyuları 2x güç kullanır",
    SuperSteelMill: "Hearts of Iron(Demir Kalpler)",
    SuperSteelMillDesc: "Çelik fabrikaları %50 daha az kömür ve %25 daha fazla demir ve %25 daha fazla güç kullanıyor",
    AlSemiconductor: "Alüminyum Devre",
    AlSemiconductorDesc: "Devre dökümhaneleri bakır yerine alüminyum kullanıyor",
    CostSaver: "Maliyet Tasarrufu",
    CostSaverDesc: "Bir binanın girdisi çıktısından daha pahalıysa üretimi durdurur.",
    CostSaverBuildingDesc:
        "Maliyet Tasarrufu politikası aktifse, karlılığına göre üretim otomatik olarak açılıp kapanacaktır.",
    CostSaverBuildingWarning: "Maliyet Tasarrufu politikası etkinse, üretimi manuel olarak değiştiremezsiniz",
    GlassUseCoal: "Kara Cam",
    GlassUseCoalDesc: "Cam fabrikaları %50 daha fazla kömür ve %50 daha az silikon kullanıyor",
    AdjacentBonusOnlyOutput: "Bitişiklik Bonusu +",
    AdjacentBonusOnlyOutputDesc:
        "Bitişiklik bonusu daha fazla giriş gerektirmez ancak daha fazla güç kullanır ve yalnızca %50 etkilidir",
    IronMine2xOutput: "Ağır Demir",
    IronMine2xOutputDesc: "Demir madenleri 2x demir üretir ancak demir taşıma maliyeti 2x yakıttır",
    SolarPanelAlwaysWork: "İngiltere",
    SolarPanelAlwaysWorkDesc: "Güneş paneli zamanın %100'ünde çalışır ancak %60 daha az güç üretir",
    SteelScience: "Çelik Yoluyla Bilgi",
    SteelScienceDesc: "Çelik fabrikaları 2x girdi kullanır ve ekstra bilim üretir",
    ShoppingSpree: "Alışveriş Çılgınlığı",
    ShoppingSpreeDesc:
        "Bir kaynağın çıktı kapasitesi yetersiz kalırsa, eksiklik miktarını Ticaret Merkezi'nden otomatik olarak satın alır (Kaynağın otomatik satışı açıksa, dikkate alınmaz)",
    ShoppingSpreeTradeCenterDesc:
        "💡 Alışveriş Çılgınlığı politikası etkinse, Ticaret Merkezi'nden otomatik olarak kıtlıkta olan kaynakları satın alacak",
    ExtraPolicyPoints: "Politiksel Lobici",
    CrAlloyUseFe: "Lityumsuz Krom",
    CrAlloyUseFeDesc: "Krom Alaşım Tesisleri Lityum kullanmaz, bunun yerine 2x Demir kullanır",
    DoubleTileModifier: "Doğanın Gücü",
    TileModifierOutputOnly: "Karo Bonusu +",
    GasPlantPetrol: "Gaz Sıvılaştırıcı",
    GasPlantPetrolDesc: "Gaz santralleri petrol üretmek için ekstra gaz kullanır",
    CoalPlantFuel: "Kömür Sıvılaştırıcı",
    CoalPlantFuelDesc: "Kömür santralleri petrol üretmek için ekstra kömür kullanıyor",
    Welcome: "Hoşgeldin",
    SeeTutorialAgain: "Eğitimi Göster",
    HelpTranslateTheGame: "Dil çevirisine yardımcı ol",
    NextTutorial: "Sıradaki",
    Tutorial1:
        "Industry Idle, fabrikalar🏭 inşa ettiğiniz, ürünler📦 ürettiğiniz ve para kazandığınız💸 bir <em>kaynak yönetimi</em> oyunudur.<br><br>Başlamak için bazı temel kavramlara göz atalım - çok uzun sürmez, söz veriyorum.",
    Tutorial2:
        "Tüm binaların güce ihtiyacı vardır⚡, güç üreten bir <em>rüzgar türbinine</em> sahipsiniz. Mevcut güç kaynağınızı üst çubuğun sol tarafında görebilirsiniz.<br><br>Rüzgar türbinlerinin yalnızca <em>%80</em> oranında çalıştığını fark etmiş olabilirsiniz. İstikrarlı güç üreten başka tipte enerji santralleri inşa etmeyi düşünebilirsiniz.",
    Tutorial3:
        "Haritada çok sayıda <em>kaynak birikintisi</em> var. Kaynakları çıkarmak için karşılık gelen yatağın <em>üstüne</em> madenler⛏️ inşa etmeniz gerekir..<br><br>Örneğin, bir petrol yatağından <em>petrol</em> çıkaran bir <em>petrol kuyunuz🛢️</em> var.<br></br>Kaynak birikintileri sınırsızdır - çalışacakları konusunda endişelenmenize gerek yok dışarı. Herhangi bir boş karo üzerine maden ocakları dışında başka binalar da inşa edilebilir.",
    Tutorial5:
        "Para kazanmak için kaynaklarınızı ticaret merkezi aracılığıyla ihraç etmeniz gerekir. Bunu yapmak için, o kaynak için <em>otomatik satışı</em> etkinleştirmeniz yeterlidir.<br></br>Ayrıca ticaret merkezinden kaynak da satın alabilirsiniz. <em>Bir kaynak satın alırsanız fiyatı yükselteceğinizi</em> ve bir kaynak satarsanız fiyatı düşüreceğinizi unutmayın.<br><br>Piyasa <em>dalgalı</em > ve fiyat📈 düzenli olarak değişir.",
    Tutorial6:
        "Yeni binalar inşa etmek için önce <em>araştırma laboratuvarında kilidini açmalısın 🧪</em>. Araştırma laboratuvarı ayrıca bilimi araştırma puanlarına dönüştürür.<br><br>Rüzgar türbininiz (ve diğer enerji santralleriniz) çalışırken az miktarda bilim üretir. Ve daha sonra bilimi ilerletmek için okul🏫 ve diğer özel binalar inşa edebilirsiniz.<br><br>Artık tüm temel bilgileri öğrendiniz, ekonominizi oluşturmaya başlayın! İşte sana hızlı bir başlangıç yapmak için biraz <em>nakit💸</em> ve <em>petrol⛽</em>.",
    WelcomePlay: "Oyna",
    WelcomePlayMuted: "Oyna (🔇Müzik)",
    Chat: "Sohbet",
    RestoreFromBackup: "Yedekten Geri Yükle",
    RestoreFromBackupFail: "Steam Cloud'dan yedekleme geri yüklenemedi: bir yedekleme olduğundan emin misiniz?",
    RestoreFromBackupTitle: "Emin misin?",
    RestoreFromBackupDesc:
        "Yerel kaydınız kaybolmadığı sürece normalde bulut yedeklemesinden geri yüklemeniz gerekmez. Bulut yedekleme, yerel kaydetmenizden biraz daha eskidir",
    ChangeName: "İsmini Değiştir",
    SaveName: "Kaydet",
    NameValidationRule: "Adınız yalnızca harf ve rakamlardan oluşmalı ve 5-15 karakter arasında olmalıdır.",
    NameValidationRuleProfanity: "Adınız küfür içermemelidir",
    ChatMessageRateLimit: "Yalnızca her 10 saniyede bir yeni sohbet mesajı gönderebilirsiniz.",
    NameSaved: "İsmin başarıyla değiştirildi",
    NoMessages: "Yeni mesaj yok",
    Leaderboard: "Lider Sıralaması",
    Name: "İsim",
    Tips1: "Hisse senedi derecelendirmelerinin 5 seviyesi vardır: Satın Al, Yüksek Performans, Tut, Düşük Performans ve Satış",
    Tips2: "Stok modunu açmadığınız sürece, üretim için zaten yeterli kaynak varsa binalar taşımayı durdurur",
    Tips3: "Kaynak taşımacılığı için yakıt maliyeti, mesafeye ve kaynak miktarına göre belirlenir",
    Tips4: "Binalar, yalnızca haritada bulunan miktar girdi kapasitesini aşarsa bir kaynağı taşıyacaktır.",
    Tips5: "Binalar, yalnızca o kaynak için otomatik satış kapalıysa Ticaret Merkezi'nden bir kaynağı taşıyacaktır.",
    Tips6: "İlgili girdi kapasitesi bölümünün altında bir kaynağın yakıt maliyetini görebilirsiniz.",
    Tips7: "Bir kaynak satın alırsanız, fiyatı yükseltirsiniz. Bir kaynak satarsanız, fiyatı düşürürsünüz",
    Tips8: "İstatistik Bürosu'nda her kaynağın miktarı ve zaman içindeki değişimi için grafiği görebilirsiniz.",
    Tips9: "Bir bina için ihtiyaç duyulan araştırma puanları, girdi kaynaklarının piyasa fiyatına göre belirlenir.",
    Tips10: "Farklı kaynaklar piyasada farklı şekilde fiyatlandırılır - her zaman piyasa oynaklığına hazırlıklı olun",
    Tips11: "Üretiminizi genişletmeden önce her zaman güç ve yakıt kaynağınızı kontrol etmek iyi bir fikirdir.",
    FPS30: "Daha az batarya tüketimi",
    OfflineModeDesc:
        "Sunucuya bağlanılamıyor: çevrimdışı kazançlar oluşturulmayacak. Lütfen internet bağlantınızı kontrol edin",
    OptOut: "Vazgeçmek",
    OptIn: "Sıfırla ve Etkinleştir",
    LeaderboardOptOut: "Lider Sıralamasını Devre Dışı Bırakma",
    LeaderboardOptIn: "Lider Sıralamasını Sıfırla ve Etkinleştir",
    LeaderboardOptInDesc: "Lider Sıralamasını yeniden etkinleştirebilmeniz için verilerinizin SIFIRLANMASI gerekiyor, emin misiniz?",
    RewardAdsFailed: "Ödül videosu tamamlanmadı",
    OfflineEarningDoubleSuccess: "Çevrimdışı kazancınızı ikiye katladınız",
    FPS30Desc:
        "Enerji tasarrufu modunu açın, oyunu 60FPS yerine 30FPS'de çalıştıracaktır. Bu, pilinizin daha uzun süre dayanmasını sağlar",
    HighlightAll: 'Vurgula "%{type}"',
    HighlightInput: "🔍 %{type} Girdiyi Vurgulayın",
    HighlightOutput: "🔍 %{type} Çıktıyı Vurgulayın",
    RunOutIn: "%{time} içinde çıktı",
    SwissBank: "Swiss Bankası",
    SwissMoney: "%{money} 💵",
    PrestigeDesc: "Yeni bir şehirde başlarsan, %{money} 💵 alacaksın",
    RestorePurchases: "Satın Alınanları Geri Yükle",
    RestorePurchasesSuccess: "Satın aldığınız ürünler geri yüklendi",
    RestorePurchasesFailed: "Satın aldığınız ürünler geri yüklenmedi",
    ExpansionPacks: "Genişletme Paketi",
    ExpansionPack1: "Genişletme Paketi 1",
    RequireExpansionPack1: "Genişletme Paketi 1",
    RequireExpansionPack1Desc: "Bu yalnızca Genişletme Paketi 1 için kullanılabilir",
    RequireAnyExpansionPack: "Genişletme Paketine Özel",
    RequireAnyExpansionPackDesc: "Bu özellik, genişletme paketlerinden en az birine sahip olmanızı gerektirir.",
    HideRewardAd: "Reklamları gizle",
    HideRewardAdDesc:
        "Tüm oyun içi reklamlar isteğe bağlı ödüllü reklamlardır. Bu, tüm ödüllü reklam seçeneklerini oyundan gizleyecektir.",
    HideDiscordBanner: "Discord Afişini Gizle",
    HideDiscordBannerDesc: "Discord'u ve genel merkezdeki vitrin afişini gizle",
    HideChat: "Sohbet Mesajını Gizle",
    PurchaseFailed: "Satın Alma İşlemi Tamamlanmadı",
    PurchaseSteamContinue: "Lütfen satın alma işleminizi Steam'de tamamlayın",
    PurchaseSuccess: "Satın alma işlemi tamamlandı, desteğiniz için teşekkürler",
    PrestigeCurrency: "Swiss Parası 💵",
    RestartDesc: "💡 Sadece yeniden başlatmak mı istiyorsunuz? Yukarıdaki Yeni Bir Şehirde Başla'ya dokunabilir ve mevcut şehrinizi seçebilirsiniz.",
    PrestigeGoBack: "Geri dön",
    ProductionMultiplier: "Üretim Katlayıcı",
    ProductionMultiplierDesc:
        "Tüm binalarınızın üretim kapasitesinde artış (madenler, fabrikalar, enerji santralleri, bilim ve kültür binaları dahil)",
    FuelCostDiscount: "Yakıt Maliyeti İndirimi",
    FuelCostDiscountDesc: "Kaynakları taşırken yakıt maliyetinde indirim sağlar",
    BuildingPermitCostDivider: "Yapı İzni Maliyet Bölücü",
    BuildingPermitCostDividerDesc: "İnşaat izni maliyetini bu bölücüye bölün",
    ExtraAdjacentBonus: "Ekstra Bitişiklik Bonusu",
    ExtraAdjacentBonusDesc: "Aynı tipteki her bitişik çalışan bina için ekstra bonus kapasite",
    PrestigeAlertTitle: "Emin misin?",
    PrestigeAlertContent:
        "Şirketiniz satılacak ve %{amount} Swiss parasına dönüştürülecek ve %{city}'de yeni bir şirket kuracaksınız",
    PrestigeCurrencyDesc:
        "Bu, gizli Swiss Bankası hesabınızdaki paradır, yeni bir şehirde başladığınızda yanınızda taşıyabilirsiniz.",
    Prestige: "Nakit",
    Cancel: "İptal",
    SaveFileCorrupted: "Bozuk Dosyayı Kaydet",
    LoadGameError: "Oyun Yüklenemedi",
    LoadGameErrorMessage: "Hata Mesajı: %{message}",
    LoadGameErrorDesc: "Lütfen İnternet bağlantınızı kontrol edin. Sorun devam ederse, lütfen destekle iletişime geçin",
    ExpansionPackIncompatible:
        "Genişletme paketleri içeren bir kaydı içe aktarıyorsunuz ancak oyununuz gerekli genişletme paketlerine sahip değil",
    CashIn: "Nakit",
    CurrentCity: "Şu anki şehir",
    CashInDesc:
        "Yeni bir şehirde başlarsanız, bu tutarı Swiss Banka hesabınıza alacaksınız. Şirketinizin piyasa değerine bağlıdır ve Swiss parası kazanabilmeniz için %{amount} değerine ulaşması gerekir",
    CitySize: "Harita Genişliği",
    GridType: "Klavuz Çizgileri",
    StartInThisCity: "Şehirde Başla %{city}",
    CityBonus: "Şehir Bonusu",
    ResourceTilePercentage: "Kaynaklar",
    MapSquareGrid: "Büyüklük",
    MapHexGrid: "Altıgen",
    Stockholm: "Stockholm",
    Rotterdam: "Rotterdam",
    Oslo: "Oslo",
    StPetersburg: "St. Petersburg",
    Hamburg: "Hamburg",
    HamburgBonus:
        "<li>Zeppelin fabrikalarının kilidi açıldı</li><li>Yarı iletken fabrikalar 2x üretkenliğe sahip</li><li>Tersaneler 2x kapasiteye sahip</li><li>Araba fabrikaları 2x kapasiteye sahip</li><li>Li-ion batarya fabrikaların kilidini açar</li>",
    Toulouse: "Toulouse",
    Rome: "Roma",
    RomeBonus:
        "<li>Kolezyumların kilidi açıldı</li><li>Kolezyumlar 2x üretkenliğe sahip</li><li>5. seviye politika merkeziyle başlayın</li><li>Operaların kapasitesi 2x olur</li><li>Kayıt stüdyoları da kültür üretimi yapar</li>",
    Detroit: "Detroit",
    Boston: "Boston",
    BostonBonus:
        "<li>5. seviye araştırma laboratuvarıyla başlayın</li><li>Politeknikler açılır</li><li>Politeknikler 2x kapasiteye sahiptir</li><li>Okullar 2x kapasiteye sahiptir</li><li>Üniversite 2 kat üretkenliğe sahiptir< /li>",
    HideNotProducing: "Üretilmeyen kaynakları gizleyin",
    SortByStorage: "Depo",
    SortByName: "İsim",
    PlayerTrade: "Oyuncu Ticareti",
    AddTradeFail: "İşleminiz eklenemedi",
    AddTradeExceedMaximumTrade:
        "Yalnızca maksimum %{number} aktif işleminiz olabilir, lütfen önce birini talep edin veya iptal edin",
    AddTradeSuccess: "İşleminiz başarıyla eklendi",
    ClaimTradeFail: "Bu ticaret üzerinde hak talebinde bulunulamadı, lütfen daha sonra tekrar deneyin.",
    CancelTradeSuccess: "İşleminiz başarıyla iptal edildi",
    CancelTradeFail: "Bu ticaret iptal edilemedi, lütfen daha sonra tekrar deneyin",
    AcceptTradeFail: "Bu ticaret kabul edilemedi, lütfen daha sonra tekrar deneyin",
    PlayerTradeBanner: "Diğer Oyuncularla Kaynak Ticareti Yapın",
    PlayerTradeResource: "Kaynak",
    PlayerTradeAmount: "Miktar",
    PlayerTradePrice: "Fiyat $",
    PlayerTradeValue: "Değer $",
    PlayerTradeWaiting: "Bekleniyor...",
    AddTrade: "Ticaret Ekle",
    AcceptTrade: "Kabul Et",
    CancelTrade: "İptal Et",
    ClaimTrade: "Talep",
    FailedToImportSave: "Kaydetme İçe Aktarılamadı",
    CancelActiveTradeFirst: "Aktif oyuncu takaslarınız var, lütfen önce onları iptal edin/talep edin",
    PlayerTradeValidRange: "Menzil: %{min} ~ %{max}",
    PlayerTradeUnavailable:
        "Oyuncularla ticaret yapabilmek için üretimde ve depoda en az bir kaynağa sahip olmanız gerekir.",
    PlayerTradeToClaim: "Oyuncu Ticaretinde talep edilecek %{num} yeni ticaretiniz var",
    PowerBank: "Güç Bankası",
    PowerBankBuildDesc: "Fazla gücü depolayın ve kesinti sırasında güç kaynağı sağlayın",
    WarehouseBuildDesc: "Depolar herhangi bir kaynağı taşıyabilir ve depolayabilir",
    PowerBankChargeSpeed: "Şarj hızı",
    PowerBankPowerLeft: "Kalan Güç",
    PowerBankMoreCapacity: "Batarya koruyucu",
    PowerBankMoreCapacityDesc: "Güç bankaları %50 hızda şarj olur ancak %50 daha fazla kapasiteye sahiptir",
    PowerBankNotWorking: "⛔ Güç bankaları yalnızca bir elektrik santralinin yanında çalışır",
    ColorTheme: "Renk teması",
    ColorThemeDesc: "Oyun simgeleri, vurgulama, ızgara ve arka plan için renk teması. YENİDEN YÜKLEME GEREKTİRİR",
    SiliconMine2xOutput: "Silikon Vadisi",
    SiliconMine2xOutputDesc:
        "Silikon madenleri 2x silikon üretir ancak %50 daha fazla güç kullanır ve silikon taşıma maliyeti %50 daha fazla yakıt harcar",
    CoalMine2xOutput: "Sanayi devrimi",
    CoalMine2xOutputDesc: "Kömür madenleri 2x kömür üretir ancak %50 daha fazla güç kullanır ve kömür nakliyesi %50 daha fazla yakıt harcar",
    AlMine2xOutput: "Alüminyum Eritme",
    AlMine2xOutputDesc: "Alüminyum madenleri 2x alüminyum üretir ve 2x daha fazla güç kullanır",
    LoggingCamp2xOutput: "Ormansızlaşma",
    LoggingCamp2xOutputDesc: "Ağaç kesme kampları 2x odun üretir ve odun taşıma maliyeti 2x yakıt",
    PowerBankLeft: "Güç Bankası",
    ColorThemeEditor: "Renk Teması Düzenleyici",
    ColorThemeEditorDesc: "Geçerli renk temasındaki renkleri geçersiz kılabilirsiniz. Şu anda %{num} geçersiz kılmanız var",
    ColorThemeEditorSave: "Kaydet",
    ColorThemeEditorReset: "Sıfırla",
    ColorThemeEditorResetAll: "Hepsini Sıfırla",
    NewMessageMentions: "Yeni bir mesaj sizden bahsediyor: %{message}",
    HideChatMentions: "Sohbet Bahsetmelerini Gizle",
    HideChatMentionsDesc: "Bir sohbet mesajı benden bahsettiğinde sesli ve toast(tost) bildirimini gizle,",
    AcceptTradeFailRateLimit: "Her %{time} saniyede yalnızca bir işlemi kabul edebilirsiniz",
    DowngradeBuilding: "Düşürme",
    WarehouseAddInput: "Rota Ekle",
    WarehouseTapToSelect: "Seçmek için Haritaya dokunun...",
    WarehouseFindOnMap: "🔍 Haritada Bul",
    WarehouseRemoveRoute: "Kaldır",
    WarehouseAddRouteFail: "Rota eklenemedi: seçilen karo geçerli bir kaynak değil",
    LevelN: "Seviye %{level}",
    Surplus: "Fazlalık",
    Production: "Üretim",
    Consumption: "Tüketim",
    WarehouseInputCapacityDescV2: "Tüm rotalar arasında eşit olarak bölünmüş toplam dahili taşıma kapasitesi",
    PlayerCountryFlag: "Oyuncu bayrağı",
    PlayerCountryChooseFlag: "Ülke Kodu Alfabetik Sırasıyla",
    WindTurbineAlwaysWork: "Rüzgar yükseliyor",
    WindTurbineAlwaysWorkDesc: "Rüzgar türbinleri zamanın %100'ünde çalışır ancak %30 daha az güç üretir",
    BookPublisherScience: "Bilim Edebiyat",
    BookPublisherScienceDesc: "Kitap yayımcıları kültür yerine bilim üretir",
    BatteryFuelEconomy: "Şarj edilebilir batarya",
    BatteryFuelEconomyDesc: "Batarya yakıt ekonomisi %100 iyileşir (yani %50 yakıt maliyeti)",
    ShowTheoreticalInputOutputCapacity: "Teorik girdi/çıktı kapasitesini göster",
    SpecialTransportCost: "Özel Taşıma Maliyetli Kaynaklar",
    FreeTransportCost: "Ücretsiz Taşıma Maliyetli Kaynaklar",
    Osaka: "Osaka",
    OsakaBonus:
        "<li>Kaynaklar kümeler halinde ortaya çıkma eğilimindedir</li><li>Depo %50 daha fazla yakıt tasarrufu sağlar</li><li>Benzersiz bina: manga yayıncısı</li><li>Benzersiz bina: anime stüdyosu</li><li >Yarı iletken fabrikalar 2 kat üretkenliğe sahiptir</li><li>Li-ion pil fabrikaları 2 kat kapasiteye sahiptir</li><li>Pil fabrikalarının kilidi açılır</li><li>Pil fabrikaları 2 kat kapasiteye sahiptir</li><li >Pil yakıt ekonomisi %100 oranında iyileşir</li><li>Pil fabrikaları kömür gerektirmez</li><li>100.000 pil ile başlayın</li>",
    HideChatDescV2: "Alt araç çubuğundan sohbet mesajını gizleyin. Sohbet mesajlarını göstererek şunları kabul etmiş olursunuz:",
    HideChatDescV2ToS: "Kullanım Şartları",
    IntegratedCircuitFab: "Entegre Devre Fabrikası",
    MangaPublisher: "Manga Yayımcısı",
    Manga: "Manga",
    AnimeStudio: "Anime Stüdyosu",
    Anime: "Anime",
    PlayerTradeAction: "Eylem",
    PlayerTradeBuy: "Satın al",
    PlayerTradeSell: "Sat",
    PlayerTradeBid: "Teklif et",
    PlayerTradeAsk: "Sor",
    ClaimTradeSuccessV2: "İşleminiz başarıyla talep edildi: %{cashOrResource}",
    AcceptTradeSuccessV2: "Bu ticaret sizin tarafınızdan kabul edildi: %{cashOrResource}",
    ResourceExplorer: "Kaynak Kaşifi",
    ResourceExplorerDesc: "Boş bir harita döşemesinden kaynakları çıkarmanıza olanak tanır",
    ResourceExplorerDescLong: "💡 Kaynak Kaşiflerinin bitişiklik bonusu yoktur. Güç kullanımı kaynağa göre değişir",
    ProductionSettings: "Üretim Ayarları",
    PlayerTradePartialFillTitle: "Doldurma Yüzdesini Seçin",
    PlayerTradeAmountNotValidV2: "İzin verilen minimum işlem miktarı 1'dir",
    PlayerTradeOptOut: "You have opted out of the leaderboard, you cannot trade with other players",
    FirstTimeReadGuide: "💡 Nasıl oynanacağı konusunda biraz yardıma mı ihtiyacınız var? Başlangıç ​​kılavuzunu okumak için dokunun!",
    ReadSteamGuideV2: "Oyun Kılavuzları",
    ReadSteamGuideV2Desc: "Steam'de topluluk tarafından oluşturulan kılavuzları okuyabilir ve kendinizinkini de oluşturabilirsiniz",
    ChatMessageTooLong: "Sohbet mesajınız izin verilen maksimum karakteri aştı",
    ChatPlaceholderV2: "Mesajınızı yazın: maks. %{uzunluk} karakter",
    ProfitBreakdownOutput: "%{res} Çıktı",
    ProfitBreakdownInput: "%{res} Girdi",
    ProfitBreakdownFuel: "Yakıt maliyeti",
    BuildingProfit: "Kâr",
    RestoreBackup: "Onarmak",
    SteamLogin: "Steam Üzerinden Giriş Yapın",
    SteamLoginDialogDesc:
        "Yerel kaydınızda Genişletme Paketi etkin, devam etmek için Steam üzerinden oturum açmanız gerekiyor. Veya YEREL KAYDINIZI SİLİP baştan başlayabilirsiniz",
    SteamLoginDesc: "Steam'de genişletme paketlerine sahipseniz, oturum açtıktan sonra web üzerinde genişletme paketleriyle oynayabilirsiniz.",
    SteamLoginYes: "Kayıt ol",
    SteamLoginNo: "Sil ve Baştan Başla",
    KungFuDojo: "Kung-Fu Dojosu",
    KungFu: "Kung-Fu",
    TaiChi: "Tai-Chi",
    TaiChiDojo: "Tai-Chi Dojosu",
    HongKong: "Hong Kong",
    FreeTransportToTradeCenter: "Uluslararası İhracat Ticareti",
    FreeTransportToTradeCenterDesc:
        "Ticaret merkezine ulaşım yakıt maliyeti gerektirmez ancak ticaret merkezinden ulaşım %50 daha fazla yakıt maliyetine sahiptir.",
    TaiChi10xCulture: "Doğu'nun incisi",
    PlayerTradeYouHave: "Depoda: %{amount}",
    FiberFactory: "İplik Fabrikası",
    Fiber: "İplik",
    Achievements: "Başarılar",
    AchievementsDesc: "%{total} başarıdan %{number} tanesine ulaştınız",
    AchievementsReward: "Ödül: Swiss Parası +%{swiss}",
    AchievementsRewardToast: "Ödülü aldınız: Swiss Parası +%{swiss}",
    AchievementsClaim: "Topla",
    AchievementsToast: "%{name} elde ettiniz, ödülünüzü Karargahtan alın",
    AchievementStockholm100: "Birinci sınıf Viking",
    AchievementStockholm100Desc: "Stockholm'de tek seferde 100 Swiss Parası kazanın",
    AchievementStockholm500: "Mezun Viking",
    AchievementStockholm500Desc: "Stockholm'de tek seferde 500 Swiss Parası kazanın",
    AchievementStockholm1000: "Deneyimli Viking",
    AchievementStockholm1000Desc: "Stockholm'de tek seferde 1000 Swiss Parası kazanın",
    AchievementOslo100: "Norveçli Petrol Hobisi",
    AchievementOslo100Desc: "Tek seferde Oslo'da 100 Swiss Parası kazanın",
    AchievementOslo500: "Norveçli Petrol Meraklısı",
    AchievementOslo500Desc: "Tek seferde Oslo'da 500 Swiss Parası kazanın",
    AchievementOslo1000: "Norveç Petrol Kralı",
    AchievementOslo1000Desc: "Tek seferde Oslo'da 1000 Swiss Parası kazanın",
    AchievementRotterdam100: "Fırıldak Sahibi",
    AchievementRotterdam100Desc: "Rotterdam'da tek seferde 100 Swiss Parası kazanın",
    AchievementRotterdam500: "Rüzgar Değirmeni Sahibi",
    AchievementRotterdam500Desc: "Rotterdam'da tek seferde 500 Swiss Parası kazanın",
    AchievementRotterdam1000: "Rüzgar Türbini Sahibi",
    AchievementRotterdam1000Desc: "Rotterdam'da tek seferde 1000 Swiss Parası kazanın",
    AchievementDetroit100: "Yerel Araba Satıcısı",
    AchievementDetroit100Desc: "Tek seferde Detroit'te 100 Swiss Parası kazanın",
    AchievementDetroit500: "Bölgesel Araç Distribütörü",
    AchievementDetroit500Desc: "Tek seferde Detroit'te 500 Swiss Parası kazanın",
    AchievementDetroit1000: "Ulusal Otomobil Tekeli",
    AchievementDetroit1000Desc: "Tek seferde Detroit'te 1000 Swiss Parası kazanın",
    AchievementBoston100: "Para Kazanma Lisansı",
    AchievementBoston100Desc: "Boston'da tek seferde 100 Swiss Parası kazanın",
    AchievementBoston500: "Para Kazanma Ustası",
    AchievementBoston500Desc: "Boston'da tek seferde 500 Swiss Parası kazanın",
    AchievementBoston1000: "Para Basımı",
    AchievementBoston1000Desc: "Boston'da tek seferde 1000 Swiss Parası kazanın",
    AchievementRome100: "Diocletianus",
    AchievementRome100Desc: "Tek seferde Roma'da 100 Swiss Parası kazanın",
    AchievementRome500: "Büyük Konstantin",
    AchievementRome500Desc: "Tek seferde Roma'da 500 Swiss Parası kazanın",
    AchievementRome1000: "Sezar Augustus",
    AchievementRome1000Desc: "Tek seferde Roma'da 1000 Swiss Parası kazanın",
    AchievementHamburg100: "Almanya",
    AchievementHamburg100Desc: "Hamburg'da tek seferde 100 Swiss Parası kazanın",
    AchievementHamburg500: "Vatan",
    AchievementHamburg500Desc: "Hamburg'da tek seferde 500 Swiss Parası kazanın",
    AchievementHamburg1000: "Graf Zeppelin",
    AchievementHamburg1000Desc: "Hamburg'da tek seferde 1000 Swiss Parası kazanın",
    AchievementToulouse100: "Jetliner A310",
    AchievementToulouse100Desc: "Toulouse'da tek seferde 100 Swiss Parası kazanın",
    AchievementToulouse500: "Jetliner A330",
    AchievementToulouse500Desc: "Toulouse'da tek seferde Swiss Parası kazanın",
    AchievementToulouse1000: "Jetliner A380",
    AchievementToulouse1000Desc: "Toulouse'da tek seferde 1000 Swiss Parası kazanın",
    AchievementHongKong100: "Hobi Tüccarı",
    AchievementHongKong100Desc: "Tek seferde Hong Kong'da 100 Swiss Parası kazanın",
    AchievementHongKong500: "Profesyonel Komisyoncu",
    AchievementHongKong500Desc: "Tek seferde Hong Kong'da 500 Swiss Parası kazanın",
    AchievementHongKong1000: "Serbest Fon Yöneticisi",
    AchievementHongKong1000Desc: "Tek seferde Hong Kong'da 1000 Swiss Parası kazanın",
    AchievementStPetersburg100: "Büyük Dük",
    AchievementStPetersburg100Desc: "St. Petersburg'da tek seferde 100 Swiss Parası kazanın",
    AchievementStPetersburg500: "Tsesarevich",
    AchievementStPetersburg500Desc: "St. Petersburg'da tek seferde 500 Swiss Parası kazanın",
    AchievementStPetersburg1000: "Tüm Rusya'nın Çarı",
    AchievementStPetersburg1000Desc: "St. Petersburg'da tek seferde 1000 Swiss Parası kazanın",
    AchievementOsaka100: "Danshaku",
    AchievementOsaka100Desc: "Osaka'da tek seferde 100 Swiss Parası kazanın",
    AchievementOsaka500: "Hakushaku",
    AchievementOsaka500Desc: "Osaka'da tek seferde 500 Swiss Parası kazanın",
    AchievementOsaka1000: "Kōshaku",
    AchievementOsaka1000Desc: "Osaka'da tek seferde 1000 Swiss Parası kazanın",
    SteamAutoCloudBackup: "Steam Cloud Otomatik Yedekleme",
    SteamAutoCloudBackupFailed: "Steam Cloud Otomatik Yedekleme Başarısız Oldu: %{error}",
    SteamManualBackup: "Bulut'a kaydetmeye zorla",
    UILoading: "Yükleniyor...",
    BuildingResourceBreakdown: "Boşta Miktar Dağılımı",
    SortByDeficit: "Açık",
    SortByRunOut: "Sızmak",
    SocialNetworkInc: "Sosyal Ağ A.Ş.",
    SocialNetwork: "Sosyal ağ",
    DatabaseCompany: "Veritabanı Şirketi",
    Database: "Veritabanı",
    SatelinkInc: "Site Bağlantısı A.Ş.",
    GameStationInc: "Oyun İstasyonu A.Ş.",
    AirShuttleInc: "Hava Mekiği A.Ş.",
    AircraftCarrierFactory: "Uçak Gemisi Fabrikası",
    AircraftCarrier: "Uçak Gemisi",
    MapExclusive: "Haritaya Özel",
    ElectricCar: "Nikola Tesla",
    ElectricCarDesc: "Araba fabrikaları benzin yerine batarya kullanır ve miktarın yalnızca %50'sine ihtiyaç duyar",
    HongKongBonusV2:
        "<li>Eşsiz piyasa fiyatlandırma algoritması - fiyatlar ve hisse senedi derecelendirmesi normal dağılımı takip eder (çan eğrisi)</li><li>Piyasa güncellemeleri ve ticaret kota sıfırlamaları iki kat daha sıktır (her saat)</li><li>Araştırmanın kilidi, ticaret yoluyla açılabilir kaynaklar</li><li>Benzersiz bina: Kung-Fu Dojo</li><li>Benzersiz bina: Tai-Chi Dojo</li><li>İzin verilen maksimum aktif oyuncu takası sayısında %50 artış</li <li>Eşzamanlı 1 otomatik satışla daha başlayın</li><li>Benzersiz politika: Uluslararası İhracat Ticareti</li><li>Benzersiz politika: Doğunun İncisi</li><li>Toptan Satış Merkezi'nin yalnızca 4'e ihtiyacı var kilidini açabileceğiniz kaynaklar</li><li>100 Milyon Nakit ile Başlayın</li>",
    TaiChi10xCultureDescV2:
        "Ücretsiz Kung-fu ve Tai-chi ulaşımı. Film stüdyoları 2x kapasiteye sahiptir ancak %50 daha fazla güç kullanır",
    SettingsFullScreen: "Tam ekran",
    SettingsFullScreenDesc: "Oyunu tam ekran modunda çalıştırın. Yalnızca Steam sürümü için kullanılabilir",
    LeaderboardByAllPrestigeCurrency: "Şu ana kadar kazanılan Swiss parası",
    LeaderboardByCash: "Eldeki Mevcut Nakit",
    LeaderboardTotalValuation: "Toplam değer",
    LeaderboardDescV2: "En iyi oyuncuların nerede olduğunu görün",
    LastUpdatedAt: "Son Güncelleme Tarihi",
    DetroitBonusV3:
        "<li>Motor fabrikaları açıldı,</li><li>Motor fabrikaları 2x üretkenliğe sahip</li><li>Araba fabrikaları 2x kapasiteye sahip</li><li>Otomobil fabrikaları benzin yerine gaz kullanıyor</li><li>Ücretsiz araba taşımacılığı</li><li>Nikola Tesla poliçe ücretsizdir</li><li>Tren fabrikaları 2x kapasiteye sahiptir</li>",
    SaveAndExit: "Kaydet ve Oyundan Çık",
    SaveAndExitDesc:
        "Kaydet ve oyundan çık. Bu, yalnızca Steam sürümünde mevcuttur ve pencere çubuğundaki kapat düğmesiyle aynı işlevi görür.",
    AutoSellResourceWarningShortLabel: "💡Otomatik Satış",
    AutoSellResourceWarningDesc:
        "Bu kaynağı otomatik olarak satıyorsunuz, Ticaret Merkezinde depolanan miktar burada kullanılamaz",
    PlayerTradeLocalPrice: "Yerel Fiyat: %{price}",
    ChatForceScroll: "Zorla Kaydırma",
    ChatForceScrollDesc:
        "Zorla kaydırma açıksa, yeni bir mesaj olduğunda sohbet kaydırılır. Aksi takdirde, yalnızca siz zaten en alttayken kayar",
    ResourceExplorer2: "Kaynak Kaşifi 2.0",
    ConstructionCancel: "İptal",
    PolicyBlueprint: "Taslak",
    PolicyBlueprintDesc:
        "Bir binanın inşaatı otomatik olarak başlamaz - manuel olarak başlatılması gerekir (BEDAVA POLİTİKA)",
    HighlightUnderConstruction: "...inşa edilmemiş olanlar",
    HighlightUnderLevel10: "... 10. seviyenin altında olanlar",
    HighlightUnderLevel20: "... 20. seviyenin altında olanlar",
    HighlightUnderLevel30: "... 30. seviyenin altında olanlar",
    Logout: "Çıkış Yaptınız",
    ConstructionStatusQueueingV2: "kuyruk",
    ConstructionStatusPausedV2: "duraklatıldı",
    ConstructionStatusBuildingV2: "Bina",
    ConstructionStatusUnpaidV2: "Ödenmemiş",
    ConstructionStatus: "İnşaat Durumu",
    ConstructionStart: "Başlangıç",
    CostFree: "Bedava",
    PlaceBlueprint: "Ücretsiz bir bina planı yerleştirin",
    PlayerTradePriceNotValidV2: "Ticaret fiyatı %{min} ile %{max} arasında olmalıdır",
    MarketNews: "Piyasa Haberleri",
    MarketNewsApplyToYou: "Sadece sen",
    MarketNewsApplyToGlobal: "küresel",
    MarketNewsHighlightAffected: "🔍 Vurgula",
    MarketNewsFilterInput: "Tüm %{res} girdisi ",
    MarketNewsFilterOutput: "Tüm %{res} çıktısı ",
    MarketNewsFilterBoth: "Tüm %{res} girdi ve çıktısı ",
    MarketNewsIncrease: "%{percent} arttı",
    MarketNewsDecrease: "%{percent} azaldı",
    MarketNewsBuilding: "Bu bina %{num} haberden etkileniyor",
    StockholmBonusV2:
        "<li>Eşsiz bina: müzik yapımcısı</li><li>Kütük kamplarında 2x verim var</li><li>Kağıt fabrikalarının kilidi açıldı</li><li>Devre dökümhanelerinde 2x üretkenlik var</li><li>Bilim Edebiyatı politikası ücretsizdir</li>",
    FreeOilTransportV2: "Elektrikli Yağ Taşımacılığı",
    Tutorial4P1:
        "Kaynak nakliyesi yakıt maliyetidir. Birkaç yakıt türü var ve artık yakıt olarak <em>petrol⛽</em> kullanıyorsunuz. Petrol kuyusundan petrol taşıyan ve petrol üreten bir <em>petrol rafinerisine</em> sahipsiniz.<br><br>Küçük hareketli <em>noktalar</em> kaynakların gerçek zamanlı hareketini temsil eder. Seyahat mesafesini en aza indirmek için bina konumlarınızı optimize etmelisiniz. Binalarınızı<br><br><em>yükseltmek</em> çıktılarını artıracak, ancak aynı zamanda güç kullanımlarını ve gereken girdileri de artıracaktır.",
    Tutorial4P2:
        "Yakıt türünüzü <em>lojistik departmanında🚦</em> değiştirebilirsiniz - bu haritada yakıt olarak <em>doğal gazı</em> da kullanabilirsiniz.<br><br>Lojistik departmanı da şunu gösteriyor: en çok yakıt yakan ulaşım rotalarınız - buna dikkat etmek isteyeceksiniz.<br><br><em>Yakıt üretiminizin tüketimin üzerinde olduğundan emin olmayı</em> unutmayın, aksi halde koştuğunuzda üretiminiz durur yakıt bitti.<br><br>Bu olursa endişelenmeyin, ticaret merkezinden veya diğer oyunculardan acil durum yakıtı satın alabilirsiniz.",
    Tutorial5P2:
        "<em>İstatistik bürosu📊</em>, üretiminiz hakkında iyi bir genel bakış sağlar. Kaynak girdinizin ve çıktınızın ayrıntılı bir dökümünü görebilirsiniz.<br><br>Ayrıca pek çok yararlı çizelge vardır📈 - üretiminizi dengelerken bunlara başvurmak isteyeceksiniz.<br></br> <em>nakit💰, güç fazlası⚡ ve yakıt fazlası⛽</em> sayıları da sol üst köşede gösterilir - bunlardan herhangi biri kırmızıya dönerse neler olup bittiğini araştırmanız gerekir.",
    MusicProducer: "Müzik Yapımcısı",
    PlasticFiber: "Plastik İplik",
    PlasticFiberDesc: "İplik fabrikaları %50 daha fazla plastik ama %50 daha az cam kullanıyor",
    SellRefundPercentage: "Satış/Düşürme İadesi",
    SellRefundPercentageDesc:
        "Bir binayı satar veya eski sürüme geçirirseniz bu, size iade edilen nakit ve kaynak yüzdesidir.",
    SellBuildingDescV2:
        "Bir bina satmak, yatırımınızın %{percent} kadarını size iade edecek ve kaynakların %{percent} kadarı Ticaret Merkezine taşınacak",
    BuilderMoveSpeed: "İnşaatçı Hareket Hızı",
    BuilderMoveSpeedDesc: "İnşaatçıların binaları inşa etmek için hareket etme hızı",
    EBookInc: "eKitap A.Ş.",
    ResourceBooster: "Kaynak Güçlendirici",
    BuildWarningTitle: "Bina Çalışmayabilir",
    BuildWarningTitleDesc: "%{reason}. Bu karonun üzerine inşa edeceğinizden emin misiniz?",
    BuildWarningBuildAnyway: "Yine de İnşa Et",
    ResourceBoosterNotWorking: "⛔ Kaynak güçlendiriciler yalnızca maden yataklarının yanında çalışır",
    ResourceBoosterBuildings: "Güçlendirilen Binalar",
    BuildingResourceConversion: "%{resource} Dönüştür",
    AllTimeSwissMoneyEarned: "Şu ana kadar kazanılan Swiss Parası: %{number}",
    BuildingUpgradeCostDivider: "Bina Yükseltme Maliyeti Bölücü",
    AchievementSoftwareGiant: "Yazılım Devi",
    AchievementSoftwareGiantDesc:
        "Aynı harita üzerinde 10. seviye Yazılım Şirketi, 10. seviye İşletim Sistemi A.Ş., 10. seviye Veritabanı Şirketi ve 10. seviye Web Tarayıcısı kurun",
    AchievementSpaceRace: "Uzay Yarışı",
    AchievementSpaceRaceDesc:
        "Aynı harita üzerinde 10. seviye Roket Fabrikası, 10. seviye Uydu Fabrikası, 10. seviye Uzay Gemisi Fabrikası ve 10. seviye Uzay İstasyonu Fabrikası inşa edin",
    AchievementToTheMoon: "Ay'a",
    AchievementToTheMoonDesc:
        "Seviye 40 Bitcoin Kazıcı ve seviye 40 Dogecoin Kazıcı inşa edin. 1 milyar Bitcoin ve 1 milyar Dogecoin sahibi olun",
    ItsAllGreen: "Hepsi Yeşil",
    ItsAllGreenDesc: "50 üretim hattına sahip olmak ve hiç üretim açığı vermemek",
    DeepInRed: "Derin Kırmızı",
    DeepInRedDesc: "Üretim açığı olan 50 üretim hattına sahip olmak",
    UseScientificNotation: "Bilimsel Gösterimi Kullan",
    UseScientificNotationDesc: "999.9T'den büyük sayılar için bilimsel gösterimi (e notasyonu) kullanılır",
    LogoutDescV2:
        "Başka bir cihazda oturum açtınız, bu cihazda oturum kapatıldı. Tekrar oturum açabilirsiniz ancak diğer cihazın oturumu kapatılacaktır.",
    LogBackIn: "Tekrar Giriş Yap",
    ServerDisconnected:
        "Sunucuyla bağlantınız kesildi, lütfen internet bağlantınızı kontrol edin ve oyunu yeniden başlatın",
    BuildingUpgradeCostDividerDescV2: "Bina yükseltme maliyetini bu bölücüye bölün",
    ResourceBoosterDesc: "Bitişik madenlerin çıktısını artırın",
    BlockUserChatTitle: "%{user} Engelle",
    BlockUserChatAction: "Engelle",
    BlockUserChatDesc:
        "Engelleme, bu oyun oturumu sırasında etkin olacak ve oyunu yeniden başlatmadığınız sürece bunu geri alamazsınız.",
    ChangeNameCooldown: " %{hour} Saat",
    AtomicBombFactory: "Atomik Bomba Fabrikası",
    AtomicBomb: "Atomik Bomba",
    DynamiteFactory: "Dinamit Fabrikası",
    Dynamite: "Dinamit",
    NuclearMissileFactory: "Nükleer Füze Fabrikası",
    NuclearMissile: "Nuclear Missile",
    LiquidPropellantFactory: "Sıvı Sıkıştırcı Fabrikası",
    GasPropellantFactory: "Gaz Sıkıştırıcı Fabrikası",
    Propellant: "İtici",
    ProjectV2: "Proje V-2",
    ICBMFactory: "ICBM Fabrikası",
    ICBM: "ICBM",
    RadarFactory: "Radar Fabrikası",
    Radar: "Radar",
    SpaceForceCommand: "Uzay Kuvvetleri Komutanlığı",
    SpaceForce: "Uzay Kuvvetleri",
    SpaceColony: "Uzay Kolonisi",
    SpaceColonyInc: "Uzay Kolonisi",
    ProjectVostok: "Project Vostok",
    AdjacentBonusSquare: "Bitişiklik Bonusu Karesi",
    AdjacentBonusSquareDesc: "Bitişiklik bonusu %50 daha etkilidir, ancak döşeme değiştiricileri -%15'ten +%15'e ölçeklenir",
    ResourceBoosterSquare: "Kaynak Arttırıcı Karesi",
    ResourceBoosterSquareDesc:
        "Kaynak güçlendiriciler %25 daha fazla destek sağlar ancak bilim girdileri ve güç kullanımları da %25 artar",
    SteelMillx2: "Çelik Ocağı Modernizasyonu",
    SteelMillx2Desc: "Çelik fabrikaları ve paslanmaz çelik fabrikaları 2x kapasiteye sahiptir ancak 2x güç kullanır",
    FuelDynamite: "Yakıt Dinamiti",
    FuelDynamiteDesc: "Dinamit fabrikaları petrol yerine mevcut yakıtınızı kullanır",
    StPetersburgBonusV2:
        "<li>Uranyum madenlerinde 2x üretim</li><li>Uranyum zenginleştirme tesisleri 2x kapasite</li><li>Uranyum taşıma maliyeti %50 daha az yakıt</li><li>Silah taşımada bedava</li><li>Proje Vostok 2x kapasiteye sahiptir</li>",
    ToulouseBonusV2:
        "<li>Titanyum madenlerinde 2x üretim</li><li>Uranyum zenginleştirme tesislerinde 2x verimlilik</li><li>Jet motoru fabrikalarında 2x kapasite</li><li>Uçak fabrikalarında 2x verimlilik</li><li> Roket fabrikaları 2x kapasiteye sahiptir</li>",
    BuildingPermitsNeededDesc: "Yeterli inşaat izniniz olmadığı için bu bina çalışmıyor",
    BuildingPermitsNeeded: "İnşaat İzinleri Gerekli",
    BuyMissingPermits: "Eksik İnşaat İzinlerini Satın Alın",
    GPUIsBusy: "GPU'un Meşgul",
    GPUIsBusyDesc:
        "GPU başka görevlerle meşgul olduğu için işletim sisteminiz oyunun grafiklerini duraklattı. Devam etmek için oyunu yeniden yükleyebilirsiniz. Çalışmazsa, oyunu yeniden başlatmayı deneyin",
    SaveAndReloadGame: "Oyunu Kaydet ve Yeniden Yükle",
    ResearchLabCultureInput: "Rönesans",
    ResearchLabCultureInputDesc: "Araştırma Laboratuvarı 2x kapasiteye sahiptir ancak kültürü ekstra girdi olarak alır",
    GasPumpx2Output: "Yüksek Basınçlı Gaz Pompası",
    GasPumpx2OutputDesc: "Doğal gaz pompaları 2x çıkışa sahiptir ancak 2x güç kullanır",
    LeaderboardValuationPerHour: "Saat Başına Toplam Değeri",
    LeaderboardValuationPerHourPerSwiss: "Swiss Başına Saat Başına Toplam Değeri",
    LeaderboardValuationPerHourNewPlayers: "Saat Başına Toplam Değeri (< 1000 Swiss)",
    LeaderboardValuationPerBuilding: "Bina Başına Bina Değeri",
    BuildingCustomColor: "Yapı Rengi",
    BuildingCustomColorReset: "Sıfırla",
    Vancouver: "Vancouver",
    VancouverBonus:
        "<li>Her 4 farklı bina tipi, 1 ücretsiz inşaat izni verir</li><li>Benzersiz politika: Üretim Çeşitlendirme</li><li>Benzersiz bina: Akçaağaç Şurubu Fabrikası</li><li>Ücretsiz akçaağaç şurubu nakliyesi </li><li>Benzersiz yakıt türü: Akçaağaç Şurubu</li><li>Oyuncu, Uranyum ve Zenginleştirilmiş Uranyum ticareti yaparken üretime dayalı 2x vergi kredisi takas ediyor</li><li>Benzersiz ücretsiz politika: Plastik Şurup</li ><li>Oyuncak fabrikaları 2x üretkenliğe sahiptir</li><li>Oyun stüdyoları 2x kapasiteye sahiptir</li>",
    MapExtraPermitDesc: " Haritanın benzersiz bonusundan %{number} ücretsiz inşaat izni alırsınız",
    OsloBonusV3:
        "<li>Petrol rafinerilerinin kilidi açıldı</li><li>Petrol rafinerilerinin kapasitesi 2x</li><li>Elektrikli petrol taşıma politikası ücretsizdir</li><li>Gaz işleme tesislerinin kapasitesi 2x</li><li>Ücretsiz seviye 4 rüzgar türbini x1</li><li>Serbest seviye 8 petrol kuyusu x1</li><li>Serbest seviye 2 petrol rafinerisi x1</li><li>Serbest seviye 2 doğal gaz pompası x1</li>",
    ResourceBoosterPercentageV2: "💡 Bu miktar, bitişik kaynak hızlandırıcılardan %{percent} artırım içerir",
    MapleSyrup: "Akçaağaç şurubu",
    MapleSyrupFactory: "Akçaağaç Şurubu Fabrikası",
    SyrupPlastic: "Plastik Şurup",
    SyrupPlasticDesc: "Plastik kullanan tüm binalar bunun yerine akçaağaç şurubu kullanır",
    ResourceBoosterSupplyChain: "Tedarik Zinciri Güçlendirici",
    ResourceBoosterSupplyChainDesc:
        "Kaynak artırıcılar 2x güç ve bilim kullanır, ancak çalışan her maden için bir kaynak artırıcı artırır, ayrıca madenin çıktısını tüketen komşu fabrikalara kapasite artışı sağlar (fabrika yalnızca mevduat tüketmelidir)",
    ProductionDiversification: "Üretim Çeşitlendirme",
    ProductionDiversificationDesc: "Her farklı bina tipi, tüm binalara %1 ekstra kapasite sağlar.",
    ExtraPolicyPointsDescV2: "Politika merkezi, 2x politika puanı dönüştürme kapasitesine sahiptir",
    PowerRequired: "Güç Gerekli",
    AchievementVancouver100: "Bitki özü satıcısı",
    AchievementVancouver100Desc: "Tek seferde Vancouver'da 100 Swiss Parası kazanın",
    AchievementVancouver500: "Şurup Bilgini",
    AchievementVancouver500Desc: "Tek seferde Vancouver'da 500 Swiss Parası kazanın",
    AchievementVancouver1000: "canuck Fatihi",
    AchievementVancouver1000Desc: "Tek seferde Vancouver'da 1000 Swiss Parası kazanın",
    BarbariansAtTheGate: "Kapıdaki Barbarlar",
    BarbariansAtTheGateDesc: "Pazar güncellemeleri arasında 1 trilyon değerinde oyuncu ticaret kotası kullanın",
    DiversifiedProductions: "Çeşitlendirilmiş Üretimler",
    DiversifiedProductionsDesc: "Tek bir harita üzerinde 100 farklı tipte bina inşa edin",
    RealEstateTycoon: "Emlak Kralı",
    RealEstateTycoonDesc: "Tek bir haritada 400 binaya sahip olun",
    ResourceExplorer2DescV2:
        "Kaynak kaşifleri 2xçıktı üretir ancak 2x güç kullanır. Supply Chain Booster politikası etkinse ve booster'ın bitişiğinde aynı çıktıya sahip bir maden varsa, kaynak kaşifleri kaynak booster'lar tarafından desteklenebilir.",
    NoTileModifier: "Earth Is Flat",
    NoTileModifierDesc:
        "All tile modifiers are zero. This policy will deactivate Nature's Power and Tile Modifier Plus policies",
    DoubleTileModifierDescV2:
        "All tile modifiers' effect x2 - both positive and negative. This policy will deactivate Earth Is Flat policy",
    TileModifierOutputOnlyDescV2:
        "Tile modifiers only affect output instead of both input and output but are only 50% effective. This policy will deactivate Earth Is Flat policy",
    QuickLinks: "Quick Links",
    GetHelp: "Get Help",
    GetHelpBeginnerGuides: "Beginner's Guide",
    GetHelpSteamGuides: "Other Steam Guides",
    GetHelpInGameChat: "Ask In-Game Chat",
    GetHelpDiscord: "Yardım için Discordumuza katılın",
    GetHelpWiki: "Topluluk Wikisi",
    SelectATile: "Select a Tile",
    PledgeAmount: "Pledge %{amount}",
    PledgeValue: "Value $%{amount}",
    TotalPledgedValue: "Total Pledged Value",
    TotalPledgedValueDesc:
        "Your first pledge counts towards the crowdfunding goal. Subsequent pledges increase total pledged value but do not count towards the goal",
    ReturnOnPledge: "Return On Pledge",
    CrowdfundingEndIn: "End in %{time}",
    ClaimCrowdfundingReward: "Claim Reward %{amount}",
    PledgeSuccessful: "You have pledged %{amount} to this crowdfunding",
    CrowdfundingClaimSuccessful: "You have claimed %{amount} cash",
    CrowdfundingAlreadyPledged: "You've Already Pledged",
    CrowdfundingAlreadyPledgedDesc:
        "You can pledge more resources, which will increase your total pledged value (and potential return), but won't count towards crowdfunding goal",
    WholesaleCenterProducingOnly: "Wholesale Partners",
    WholesaleCenterProducingOnlyDesc:
        "Wholesale center orders only contain resources that are currently being produced (you also need to be producing the number of required resources to unlock wholesale center)",
    SoftwareCompiler: "Yazılım derleyicisi",
    SearchEngine: "Arama motoru",
    SearchEngineCompany: "Search Engine Company",
    Navy: "Navy",
    NavyCommand: "Navy Command",
    Battleship: "Battleship",
    BattleshipFactory: "Battleship Factory",
    ResourceMovementHide: "Always Hide",
    ResourceMovementShow: "Always Show",
    ResourceMovementViewport: "In Viewport",
    ResourceMovementHighlight: "On Highlight",
    ResourceMovementLine: "Line Only",
    ResourceMovement: "Resource Movement",
    ResourceMovementDesc:
        "You can choose when to show the resource movement (dots). Hiding it can improvement performance",
    CrowdfundingCashInWarning: "You have pending crowdfunding pledges - starting in a new city will forfeit them",
    ResourceBoosterBannerDescV2:
        "💡 Şuan  %{number} kadar  kaynak yükselticin var- the science input of each is scaled to the number of resource boosters you currently have",
    CrowdfundingId: "Crowdfunding %{id}",
    PatchNotes: "Patch Notes",
    PatchNotesDesc: "Read what's new in this update",
    PanelPositionLeft: "Left (Docked)",
    PanelPositionLeftFloat: "Left (Float)",
    PanelPositionRight: "Right (Docked)",
    PanelPositionRightFloat: "Right (Float)",
    PanelPositionAuto: "Auto",
    TimePlayed: "Time Played",
    ValuationPerHour: "Valuation Per Hour",
    HighPowerPriority: "High Power Priority",
    HighPowerPriorityDesc: "Switching this on will make the building draw power before other buildings",
    IndustryZone: "Industry Zone",
    IndustryZoneDesc: "Combine adjacent buildings that forms a supply chain and save building permits",
    IndustryZoneMaxBuildingLevel: "Max Building Level",
    IndustryZoneNotWorkingDesc:
        "All of its adjacent buildings should form a supply chain and are not part of other industry zones",
    PlayerTradeAutoClaim: "Automatically claim filled trades",
    MusifyInc: "Musify Inc",
    WebflixInc: "Webflix Inc",
    CloudStreaming: "Cloud Steaming",
    GameCloudInc: "GameCloud Inc",
    SuperComputerLab: "Super Computer Lab",
    SuperComputer: "Super Computer",
    SkyNetInc: "SkyNet Inc",
    SkyNet: "SkyNet",
    RobocarFactory: "Robot araba Fabrikası",
    Robocar: "Robot araba",
    WarehouseBuildingPermitSave: "Warehouse Permit Act",
    WarehouseBuildingPermitSaveDesc: "Every two warehouses provide one free building permit",
    PolicySearchPlaceholder: "Type a policy name to search",
    SwissUpgrade: "Swiss Upgrade",
    SwissUpgradeDesc: "Swiss upgrades are permanent and will carry over if you start in a new city",
    SwissBoost: "Swiss Boost",
    SwissBoostDesc: "Swiss boosts only affect your current run - and will reset if you start in a new city",
    ProductionMultipliers: "Production Multipliers",
    MultiplierMapUniqueBonus: "Haritanın özel bonusu:",
    MultiplierSwissUpgrade: "Swiss Upgrade (Permanent)",
    MultiplierSwissBoost: "Swiss Boost (This Run)",
    SwissBoostCostDivider: "Swiss Boost Cost Divider",
    SwissBoostCostDividerDesc: "Divide Swiss boost cost by this divider - only applies to multiplier/divider upgrades",
    AirForceCommand: "Air Force Command",
    AirForce: "Air Force",
    StealthFighterFactory: "Stealth Fighter Factory",
    StealthFighter: "Stealth Fighter",
    ArmyCommand: "Army Command",
    Army: "Army",
    GreenPeacekeeper: "Green Peacekeeper",
    GreenPeacekeeperDesc: "Make army, navy, air force or space force with only renewable power plants (wind/solar)",
    DotComTycoon: "DotCom Tycoon",
    DotComTycoonDesc:
        "Build a level 10 Social Network Inc, level 10 Search Engine Company, level 10 SkyNet Inc and level 10 Musify Inc on the same map",
    ConstructionNotResearched: "Not Researched",
    OfflineEarningDescV2: "Offline earning depends on your current research, production and auto sell",
    HighSpeedWarehouse: "High Speed Warehouse",
    HighSpeedWarehouseDesc:
        "Warehouses have 2x capacity and 50% faster inward and outward transport speed, but use 2x power",
    IndustryZoneMultiplierDesc: "Industry Zone Bonus",
    IndustryZoneMultiplierSwissBoost: "Industry Zone Capacity Booster",
    EarningPerMinuteV2: "Offline Earning Rate",
    OfflineResearchPoint: "Offline Research Point",
    WholesaleCenterOrderFasterV2: "Bigger Faster Wholesale",
    OfflineResearchSwissBoost: "Offline Research",
    OfflineResearchSwissBoostDesc:
        "Research points are generated while you are offline (according to your Research Lab level, Science in your warehouse and offline earning time)",
    SanJose: "San Jose",
    SanJoseBonus:
        "<li>Unique building: chip manufacturer</li><li>Unique building: FaceApp Inc</li><li>Unique building: Bitcoin Miner</li><li>All buildings that consume silicon have max tile modifier</li><li>Solar panels generate 2x power</li><li>Silicon mines have 2x output</li>",
    RotterdamBonusV2:
        "<li>Steel Mills have 2x capacity</li><li>Stainless Steel Plants have 2x capacity</li><li>Free iron transportation</li><li>Steel transportation costs 50% less fuel</li><li>Start with 2x auto sell capacity</li><li>Earth Is Flat policy is free</li>",
    ChipManufacturer: "Chip Manufacturer",
    SnapTokInc: "SnapTok Inc",
    FaceAppInc: "FaceApp Inc",
    BitcoinMiner: "Bitcoin Kazıcı",
    GalvanicBatteryFactory: "Galvanik Batarya Fabrikası",
    BaseProductionMultiplier: "Base Production",
    ShowBreakdown: "Show Breakdown",
    HideBreakdown: "Hide Breakdown",
    IndustryZoneMultiplierSwissBoostDescV2:
        "Each tier of production chain inside an industry zone provides this capacity boost to all the buildings in the same zone",
    IndustryZoneBuildingPermitDesc:
        "If an industry zone has N tiers of productions, it will provide N-2 building permits for free",
    CrowdfundingBackersReturn: "Backers: %{backers}, Current Return: %{return}",
    CrowdfundingBackersNeeded: "%{backers} More Backer(s)",
    CrowdfundingReturnBonus: "+%{return} Return",
    ReturnOnPledgeDescV2:
        "Your total return equals to total pledged value multiplied by return rates from all resources. More backers of a resource will improve its return",
    AchievementSanJose100: "Venture Hobbyist",
    AchievementSanJose100Desc: "Earn 100 Swiss Money in San Jose in a single run",
    AchievementSanJose500: "Venture Enthusiast",
    AchievementSanJose500Desc: "Earn 500 Swiss Money in San Jose in a single run",
    AchievementSanJose1000: "Venture Capitalist",
    AchievementSanJose1000Desc: "Earn 1000 Swiss Money in San Jose in a single run",
    AchievementCrowdfundingTycoon: "Crowdfunding Tycoon",
    AchievementCrowdfundingTycoonDesc: "Pledge 1Qa worth of resources in a single crowdfunding",
    AchievementCashIsKing: "Cash Is King",
    AchievementCashIsKingDesc: "Have 1Qa cash at hand in a single run",
    AchievementPowerTycoon: "Power Tycoon",
    AchievementPowerTycoonDesc: "Generate 1GW power in a single run",
    PlayerTradeFilteringNResources: "Filtering %{n} Resource(s)",
    PlayerTradeFilterResources: "Filter Resources",
    PlayerTradeFilterClear: "Clear Filters",
    ResourceExplorerAll: "Explore All Resources",
    ResourceExplorerAllDesc:
        "Resource explorers can produce all resources, including the ones that are not on the map (this DOES NOT unlock the relevant technologies)",
    ShowResourceInTopBar: "Show In Top Bar",
    LeaderboardOptOutDescV2:
        "You will no longer appear in the leaderboard. This will also disable player trade. PLEASE NOTE: if you want to enable leaderboard later, your data needs to be reset",
    PolicyPointNoCopperDesc:
        "💡 This map doesn't have copper deposits, you can activate Al Circuit policy to unlock further technologies",
    Pumpkin: "Balkabağı",
    PumpkinBattery: "Pumpkin Battery",
    PumpkinBatteryDesc: "All buildings that consume battery use pumpkin instead (BEDAVA POLİTİKA)",
    PumpkinSteel: "Balkabağı Çeliği",
    PumpkinSteelDesc: "All buildings that consume steel use pumpkin instead (BEDAVA POLİTİKA)",
    RequireExpansionPack2: "Expansion Pack 2",
    ExpansionPack2: "Expansion Pack 2",
    RequireExpansionPack2Desc: "This is only available for Expansion Pack 2",
    Reindeer: "Reindeer",
    ReindeerSilicon: "Reindeer Silicon",
    ReindeerSiliconDesc: "All buildings that consume silicon use reindeer instead (FREE POLICY)",
    ReindeerAluminum: "Reindeer Aluminum",
    ReindeerAluminumDesc: "All buildings that consume aluminum use reindeer instead (FREE POLICY)",
    SantaClauseIsComing: "Santa Clause is Coming",
    SantaClauseIsComingDesc:
        "Santa factories consume reindeer and toy and produce santa, science and culture. Santa factories have max tile modifier. Toy factories produce reindeer in addition to toy (FREE POLICY)",
    MetaRebranding: "Meta Rebranding",
    MetaRebrandingDesc:
        "Social Network Inc is renamed to Meta Inc and consumes internet, game, super computer, bitcoin and dogecoin instead",
    MetaInc: "Meta Inc",
    ImportSave: "Import Save",
    ClearMyTrades: "Clear My Trades",
    SaveVersionTooNew:
        "Your save is from %{saveVersion} but your game is %{gameVersion}. Please update your game first",
    LeaderboardByFlag: "Tabluation By Player Flag",
    LeaderboardByMap: "Tabluation By Map",
    LeaderboardByFlagPlayerFlag: "Flag",
    LeaderboardByFlagPayerCount: "#",
    LeaderboardByFlagPayerValuationPerHour: "V/H",
    LeaderboardByFlagPayerSwissMoney: "Swiss",
    PlayerTradePriceFilter: "Price Filter",
    PlayerTradeFilterBetterThanMarket: "Better than Market",
    PlayerTradeFilterAll: "All",
    PlayerTradeFilterBestPrice: "Best Price",
    CrowdfundingTotalPledgdeValueTooLarge:
        "Your Total Pledged Value for a crowdfunding cannot exceed your current Market Cap",
    BuildingSourceAuto: "Auto Source",
    BuildingSourceManual: "🔍 Manual Source",
    BuildingSourceReset: "Reset",
    BuildingSourceSelecting: "Tap On Map...",
    BuildingSourceSetOverride: "Override",
    BuildingSourceFallback: "Manual Source Fallback",
    BuildingSourceFallbackDesc:
        "How should the building transport its input if the manual source doesn't have enough? Skip - do not transport; drain - transport what's left; new - use auto source to find a new source",
    BuildingSourceFallbackSkip: "Skip",
    BuildingSourceFallbackDrain: "Drain",
    BuildingSourceFallbackAuto: "New",
    BuildingSourceFallbackMarker: "(Fallback)",
    BuildingSourceFallbackMarkerDesc: "The manual source doesn't have enough resource, fallback strategy is active",
    BuildingSourceInvalid: "Your selected source is invalid, please select a valid tile",
    RandomIsland: "Random Island",
    RandomIslandBonus:
        "<li>The map is randomized every time you start</li><li>Map size, grid type, resource deposits and unique bonuses are all randomly rolled</li><li>There is a 5-minute cool down - the reroll only happens minimum 5 minutes apart</li>",
    RandomIslandBonusDesc: "The unique bonus on Random Island is rerolled every time you start on the map",
    RandomIslandBonusCapacity: "%{building} has %{multiplier}x capacity",
    RandomIslandBonusProductivity: "%{building} has %{multiplier}x productivity",
    RandomIslandBonusResources: "Resource deposits on this map: %{deposits}",
    ValuationPerActiveMinute: "Valuation Per Active Minute",
    Perth: "Perth",
    GV: "Geothermal Vent",
    GeothermalPowerPlant: "Geothermal Power Plant",
    AdjacentExplorer: "Adjacent Explorer",
    AdjacentExplorerDesc:
        "A resource explorer produce 2x output if it's adjacent to the resource it's producing (FREE POLICY)",
    FactoryMining: "Factory Mining",
    FactoryMiningDesc:
        "A factory can mine the deposit directly from the tile if it consumes the same deposit (FREE POLICY)",
    FactoryMiningBanner: "This building is mining %{resource} directly from this tile",
    WarehouseSourceWeight: "Weight: %{weight}",
    YAxisStartsFromZero: "Y Axis From 0",
    YAxisStartsFromZeroDesc: "All graphs' Y axis will always start from 0 instead of being auto adjusted",
    OwnDLC: "Own %{number}x Expansion(s)",
    GeneralServerSuccessMessage: "Your request has completely successfully",
    GeneralServerErrorMessage: "Error from the server: %{error}",
    WarehouseInputRoutes: "Input Routes",
    WarehouseOutputRoutes: "Output Routes",
    InputCapacity: "Üretim Kapasitesi",
    MultipleSources: "Multiple Sources",
    MultipleSourcesDesc:
        "Allow the building to potentially transport resources from multiple sources during a production cycle",
    Water: "Water",
    KansasCity: "Kansas City",
    Dam: "Hydro Dam",
    DamDesc: "Hydro dam turns adjacent empty tiles into water tile",
    Farmland: "Farmland",
    FarmlandDesc: "Produce crops on top of a water tile",
    Storage: "Storage",
    Rice: "Rice",
    Corn: "Corn",
    Wheat: "Wheat",
    Soybean: "Soybean",
    Sugarcane: "Sugarcane",
    Vegetable: "Vegetable",
    FarmlandOfflineFarming: "Offline Farming",
    FarmlandOfflineFarmingDesc:
        "Farmland built on top of natural water source produce while you are offline. Subject to offline earning time and affected by Swiss upgrades",
    FarmlandProductionDesc: "💡 Farmlands only work 5 seconds out of every 10 seconds - all cycles are aligned",
    WaterPump: "Water Pump",
    Greenhouse: "Greenhouse",
    GreenhouseDesc: "Produce a crop of your choice",
    WaterEntityLevelTooHighDesc:
        "Your building level is higher than the adjacent hydro dam level. Please upgrade your hydro dam",
    AirLiquidizer: "Air Liquidizer",
    CapacitorFactory: "Capacitor Factory",
    Capacitor: "Capacitor",
    OfflineProduction: "Offline Production",
    OfflineProductionDesc: "Transporting capacitors to this building will allow it to run when you are offline",
    Moderator: "Moderator",
    FlourMill: "Flour Mill",
    Flour: "Flour",
    FlourMillAdjustMix: "Adjust Flour Mix",
    RiceFlour: "100% Gluten Free",
    RiceFlourDesc: "Flour mills consumes rice instead of wheat",
    Bread: "Bread",
    Bakery: "Bakery",
    Fodder: "Fodder",
    FodderFactory: "Fodder Factory",
    SugarRefinery: "Sugar Refinery",
    RefinedSugar: "Refined Sugar",
    ShowSupplyChain: "Show Supply Chain",
    ShowSupplyChainDesc:
        "When you highlight a building, show the whole supply chain from all upstream and downstream buildings",
    Cake: "Cake",
    ChooseARecipe: "Choose A Recipe",
    ChickenFarm: "Chicken Farm",
    Chicken: "Chicken",
    Egg: "Egg",
    CowFarm: "Cow Farm",
    Beef: "Beef",
    Milk: "Milk",
    DairyFactory: "Dairy Factory",
    Cheese: "Cheese",
    Cookie: "Cookie",
    Butter: "Butter",
    UnlockAtLevel: "Unlock At Level %{level}",
    FastFoodChain: "Fast Food Chain",
    Burger: "Burger",
    Sandwich: "Sandwich",
    StandbyMode: "Standby Mode",
    StandbyModeDesc:
        "The game's simulation will continue to run in the background but it will not render any graphics. This should significant reduce GPU usage and moderately reduce CPU usage as well",
    StandbyModeOn: "Standby Mode On",
    StandbyModeOnDesc: "The game is running in the background. Tap anywhere to exit standby mode",
    PigFarm: "Pig Farm",
    Pork: "Pork",
    SausageFactory: "Sausage Factory",
    Sausage: "Sausage",
    Hotdog: "Hotdog",
    BatchOperationDesc: "This will apply to %{number} buildings(s). Do you want to continue?",
    BatchOperationResult: "Your batch operation has completed for %{success} buildings(s)",
    StreamingMakeMeDiscoverable: "Make Me Discoverable",
    StreamingMakeMeDiscoverableDesc:
        "Allow other players to watch your gameplay. The connection is peer to peer and only your gameplay is streamed. Microphone or webcam will not be accessed",
    StreamAutoApprove: "Public Stream",
    StreamAutoApproveDesc: "Allows players to join your stream with needing you to approve individual request",
    StreamingWatch: "Watch",
    StreamingStop: "Stop",
    StreamingPlayerDisconnected: "%{player} has disconnected from the stream",
    StreamingPlayerRejected: "%{player} has declined your stream request",
    StreamingPlayerRequested: "%{player} has requested to watch your stream, go to Headquarter to accept or reject",
    StreamingSettings: "Steaming Settings",
    StreamingAvailableStreams: "Available Streams",
    StreamingAudience: "Viewers",
    StreamingStopStream: "Stop Streaming For This Viewer",
    StreamingAcceptStream: "Accept",
    StreamingRejectStream: "Reject",
    StreamingStopStreamDesc: "Stop Streaming For This Viewer",
    StreamingConnectionFailed:
        "Failed to establish a peer connection - it is very likely your network doesn't support P2P connection",
    Pizza: "Pizza",
    StreamingStartRecord: "Start Recording",
    StreamingRecordCamera: "Record A Directed's Cut",
    StreamingRecordCameraDesc:
        "Record a 10s pre-directed sequence - the camera will set to max zoom and slowly zoom out",
    StreamingStopRecord: "Stop Recording",
    StreamingRecordingReady: "Recording Is Ready",
    StreamingRecordingReadyDesc: "You can save your recording file and play it with a compatible video player",
    StreamingRecordingSave: "Save As",
    Lantern: "Lantern",
    LunarNewYear22: "Year of The Tiger",
    LunarNewYear22Desc:
        "All buildings that consume paper will use Lantern instead and will have 2x capacity. Paper mills become Paper Academy and produce culture instead",
    PaperAcademy: "Paper Academy",
    FriedRice: "Fried Rice",
    Highlight: "🔍 Highlight",
    BatchMode: "Batch Mode",
    BatchModeAll: "All",
    BatchModeAdjacent: "Adjacent",
    BatchModeCluster: "Cluster",
    BatchUpgradeToLevelX: "To Level %{level}",
    ApplyToBatch: "Apply To %{batch}",
    BatteryRecycler: "Battery Recycler",
    BatteryShell: "Battery Shell",
    StartInANewCity: "Start In A New City",
    StartInANewCityFinePrint: "(Or Restart Your Current City)",
    BatteryFuelDesc:
        "💡 After batteries are used as fuel, they will become battery shells. You can build Battery Recyclers to recycle or recharge them",
    FriedChicken: "Fried Chicken",
    Coffee: "Coffee",
    Cocoa: "Cocoa",
    CornSyrup: "Liquid Sugar",
    CornSyrupDesc: "Sugar refineries produce refined sugar with corn instead of sugarcane",
    Crop: "Crop",
    FishPond: "Fish Pond",
    Fish: "Fish",
    LoadGameErrorRetry: "Retry",
    LoadGameErrorHardReset: "Hard Reset",
    FontSizeScaling: "Font Size Scaling",
    FontSizeScalingDesc: "Change the UI font size scale. Some UI elements might look out of place. REQUIRES RELOAD",
    FrozenVegetable: "Frozen Vegetable",
    MilkPowder: "Milk Powder",
    CannedFish: "Canned Fish",
    CocoaPowder: "Cocoa Powder",
    FrozenChicken: "Frozen Chicken",
    FrozenPork: "Frozen Pork",
    CannedBeef: "Canned Beef",
    FoodProcessingPlant: "Food Processing Plant",
    KansasCityBonus:
        "<li>Farmlands and greenhouses produce 2x corn</li><li>Free corn transportation</li><li>For each level, hydro dams give a 5% boost to adjacent farmlands</li><li>Every 2 farmlands give 1 free building permit</li><li>The Sun Never Sets policy also makes farmland work 100% of the time (including offline)</li><li>2x player trade quota when trading crops</li><li>Food processing plants are unlocked</li>",
    KansasCityHydroDamBoost: "Kansas City unique bonus: this hydro dam provides %{boost} boost to adjacent farmlands",
    PerthGeothermalPowerPlantBoost:
        "Perth unique bonus: this geothermal power plant provides %{boost} boost to adjacent buildings that produce steel",
    PerthBonus:
        "<li>Building spinners rotate clockwise, which is opposite to other cities</li><li>Unique deposit: Geothermal vent</li><li>Unique building: Geothermal Power Plant</li><li>Unique policies: Adjacent Explorer (FREE), Factory Mining (FREE)</li>",
    Biofuel: "Biofuel",
    RioDeJaneiro: "Rio de Janeiro",
    RioDeJaneiroBonus:
        "<li>Unique fuel: Biofuel</li><li>Pig, cow and chicken farms produces extra biofuel</li><li>Unique building: Biofuel Power Plant</li><li>Unique building: Cristo Redentor</li><li>Resource boosters can boost pig, cow and chicken farms</li><li>Logging camps produce 2x wood</li><li>Lumber mills have 2x capacity</li><li>Frozen chicken, frozen pork and canned beef have 2x trading quota</li>",
    BiofuelPowerPlant: "Biofuel Power Plant",
    CristoRedentor: "Cristo Redentor",
    CristoRedentorBanner:
        "Cristo Redentor provides adjacent bonus to any building that has lower or equal level. Its culture consumption grows exponentially if you build more",
    CristoRedentorDesc: "Consumes culture and provide adjacent bonus to any building",
    Istanbul: "Istanbul",
    Wormhole: "Wormhole",
    WavesSurvived: "Waves Survived",
    NumberOfWormholes: "Number of Wormholes on Map",
    NextWave: "Next Wave",
    NextWaveUnitHP: "Unit HP",
    NextWaveTotalCount: "Total Units",
    NextWaveTotalCountDesc: "Total number of units that will spawn from each wormhole",
    NextWaveSpeed: "Move Speed",
    NextWaveSpawnDelay: "Spawn Frequency",
    NextWaveSpawnDelayValue: "Every %{number}s",
    NextWaveBonusMultiplier: "Bonus Multiplier",
    NextWaveBonusMultiplierValue: "%{number}x",
    NextWaveTotalDamageNeeded: "Total Damage Needed",
    NextWaveTotalReward: "Total Reward",
    StartWave: "Start Wave",
    WaveSpawned: "Spawned",
    WaveEliminated: "Eliminated",
    WaveFailed: "Failed",
    WaveRetry: "Retry",
    WaveForfeit: "Forfeit",
    Damage: "Damage",
    DefenseCommandConvert: "Convert",
    DefenseModule: "Defense Module",
    DefenseModuleAddOne: "Add A Defense Module",
    DefenseModuleRange: "Range",
    DefenseModuleDamage: "Damage",
    DefenseModuleBulletSpeed: "Bullet Speed",
    DefenseModuleAttackSpeed: "Attack Speed",
    DefenseModuleUpgrade: "Upgrade",
    DefenseModuleMaxUpgrade: "Max Upgrade",
    DefenseModuleCriticalDamageChance: "Critical Damage Chance",
    DefenseModuleCriticalDamageChanceShort: "Crit Dmg %",
    DefenseModuleCriticalDamageMultiplier: "Critical Damage Multiplier",
    DefenseModuleCriticalDamageMultiplierShort: "Crit Dmg x",
    DefenseModuleBaseModule: "Base Module",
    DefenseCommand: "Defense Command",
    DefenseCommandDesc: "Produce damage from weapons and defend your base against invaders",
    PathBlocked:
        "You cannot build on this tile as it will block all the possible paths from wormholes to your headquarter",
    WaveInProgressBuildRemoveDisabled:
        "You cannot construct buildings on the pathway or sell buildings when an invasion wave is in progress",
    ExportSaveForTransfer: "Transfer Your Save",
    ExportSaveForTransferDesc:
        "Choose this option if you want to transfer your save across devices. This will export your right to trade to your save file - you can continue to trade after importing the save file. Your current device will not be able to trade without waiting for a cooldown period",
    ExportSaveForBackup: "Backup Your Save",
    ExportSaveForBackupDesc:
        "Choose this if you simply want to take a backup of your progress. This will leave your right to trade on your current device - importing the backup save file will not restore the right to trade without waiting for a cooldown period",
    RightToTradeValid: "Right To Trade",
    RightToTradeInvalid: "No Right To Trade",
    RightToTradeInvalidDesc:
        "This is because your right to trade has been exported to another save file - you should import that save file to restore your right to trade. If you have lost that save file, you can force restore your right to trade on this save but you will be subject to a cooldown and your other save will lose the right to trade",
    ForceRestoreRightToTrade: "Force Restore (%{cooldown}-hour cooldown)",
    ImportSaveRestoreFail: "Failed to connect to the server, please check your internet connection",
    DefenseCommandConvertDesc: "Convert resources into damage at its current trade center price",
    MousewheelSensitivity: "Mousewheel Zoom Sensitivity",
    MousewheelSensitivityDesc: "Adjust the sensitivity when scrolling mousewheel to zoom in/out",
    PlayerTradeFilterWhatIHave: "Filter What I Have",
    PathTemporarilyBlocked:
        "You cannot build on this tile as there's a wave in progress. Check again after the wave is finished",
    MoveBuilding: "Move Building",
    MoveBuildingInvalidTarget: "Failed to move the building - target tile is not valid",
    MoveBuildingMoving: "Select An Empty Tile...",
    WaveAutoNext: "Auto Start",
    WaveAutoNextDesc: "After successfully defending a wave, automatically claim the reward and start the next one",
    IstanbulBonus:
        "<li>Tower defense mode - convert your weapons to damage, defend against invaders and get cash rewards for further expansion</li><li>Army commands have 2x capacity</li><li>Tank factories have 2x capacity</li><li>Gun factories have 2x capacity</li><li>Missile factories have 2x capacity</li><li>Dynamite factories have 2x productivity</li>",
    PlayerTradeCancelTitle: "Cancel This Trade?",
    PlayerTradeCancelDescV2: "The tariff paid on this trade will NOT be refunded",
    PlayerTradeCancelYes: "Cancel Trade",
    PlayerTradeCancelNo: "Don't Cancel",
    SteamAutoCloudBackupDescV3:
        "Your latest progress is saved to Steam Cloud. The game also backs up every 10 minutes - you can force a backup at any time. Loading a backup will lose the right to trade and require a force restoration (subject to cooldown)",
    BuyFromTradeCenter: "Buy from Trade Center",
    BuyFromTradeCenterBestBid: "Best bid price from player trades",
    BuyFromTradeCenterBestAsk: "Best ask price from player trades",
    BuyFromTradeCenterAveragePrice: "Average %{price}",
    PlayerTradesAvailable: "%{number} trade(s) available from players",
    SettingsShowInToolbar: "Show In Toolbar",
    AccountVerification: "Verification",
    AccountAuthenticated: "Authenticated",
    AccountNotAuthenticated: "Not Authenticated",
    AccountTrusted: "Trusted Account",
    AccountLimited: "Limited Account",
    AntiCheatPass: "Anti-Cheat Pass",
    AntiCheatFail: "Anti-Cheat Fail",
    AchievementIstanbul100: "Leo the Great",
    AchievementIstanbul100Desc: "Earn 100 Swiss Money in Istanbul in a single run",
    AchievementIstanbul500: "Justinian the Great",
    AchievementIstanbul500Desc: "Earn 500 Swiss Money in Istanbul in a single run",
    AchievementIstanbul1000: "Constantine the Great",
    AchievementIstanbul1000Desc: "Earn 1000 Swiss Money in Istanbul in a single run",
    AchievementPerth100: "Pademelon",
    AchievementPerth100Desc: "Earn 100 Swiss Money in Perth in a single run",
    AchievementPerth500: "Wallaby",
    AchievementPerth500Desc: "Earn 500 Swiss Money in Perth in a single run",
    AchievementPerth1000: "Kangaroo",
    AchievementPerth1000Desc: "Earn 1000 Swiss Money in Perth in a single run",
    AchievementKansasCity100: "Corn on the Cob",
    AchievementKansasCity100Desc: "Earn 100 Swiss Money in Kansas City in a single run",
    AchievementKansasCity500: "Corn Dog",
    AchievementKansasCity500Desc: "Earn 500 Swiss Money in Kansas City in a single run",
    AchievementKansasCity1000: "Popcorn",
    AchievementKansasCity1000Desc: "Earn 1000 Swiss Money in Kansas City in a single run",
    AchievementRioDeJaneiro100: "Leblon",
    AchievementRioDeJaneiro100Desc: "Earn 100 Swiss Money in Rio de Janeiro in a single run",
    AchievementRioDeJaneiro500: "Barra da Tijuca",
    AchievementRioDeJaneiro500Desc: "Earn 500 Swiss Money in Rio de Janeiro in a single run",
    AchievementRioDeJaneiro1000: "Copacabana",
    AchievementRioDeJaneiro1000Desc: "Earn 1000 Swiss Money in Rio de Janeiro in a single run",
    AchievementRandomIsland100: "Bernoulli",
    AchievementRandomIsland100Desc: "Earn 100 Swiss Money in Random Island in a single run",
    AchievementRandomIsland500: "Poisson",
    AchievementRandomIsland500Desc: "Earn 500 Swiss Money in Random Island in a single run",
    AchievementRandomIsland1000: "Gauss",
    AchievementRandomIsland1000Desc: "Earn 1000 Swiss Money in Random Island in a single run",
    AchievementFishPond200: "Admiral of the Fish Pond",
    AchievementFishPond200Desc: "Build 200 fish ponds on any map in a single run",
    Photogram: "Photogram",
    FineDiningRestaurant: "Fine Dining Restaurant",
    Sushi: "Sushi",
    Pastry: "Pastry",
    HappyMeal: "Happy Meal",
    Whopper: "Whopper",
    DrinkFactory: "Drink Factory",
    SoftDrink: "Soft Drink",
    Alcohol: "Alcohol",
    Wine: "Wine",
    Cocktail: "Cocktail",
    ThreeCourseMeal: "Three Course Meal",
    SixCourseMeal: "Six Course Meal",
    NineCourseMeal: "Nine Course Meal",
    IndustryZoneCapacityBoostPermanent: "Industry Zone Bonus (Permanent)",
    IndustryZoneCapacityBoostThisRun: "Industry Zone Bonus (This Run)",
    IndustryZoneMaxBuildingLevelDesc: "Max level of buildings supported within this Industry Zone",
    IndustryZoneHelp: "How Industry Zone Works?",
    IndustryZoneProductivityBoost: "Industry Zone Plus",
    ExtraBuildingPermit: "Extra Building Permit",
    ExtraBuildingPermitDesc: "Add extra building permits to your current map - this will not increase the cost curve",
    PanelPositionDescV2:
        "Show side panel on left, right or auto (depends on current selected tile). Only work in landscape mode",
    PanelHeight: "Panel Height",
    PanelHeightDesc: "Choose the height of the panel. Only work in portrait mode on mobile devices. REQUIRES RELOAD",
    AllowPortraitMode: "Enable Portrait Mode",
    AllowPortraitModeDesc:
        "This will enable portrait mode (experimental), the screen will rotate based on your phone's sensor and settings",
    IndustryZoneProductivityBoostDesc:
        "Every tier or every 10 level of an Industry Zone provide 10% output boost to buildings in it",
    Auckland: "Auckland",
    AucklandBonus:
        "<li>All deposits are found in a New Zealand shaped area at the center of the map</li><li>Unique Building: Hydro Power Plant</li><li>Unique Policy: Mine Booster</li><li>Unique Policy: Electric Fish Pond</li><li>Fish ponds can be built on any tiles</li>",
    MineBooster: "Mine Booster",
    MineBoosterDesc:
        "A working mine provides 100% capacity boost to adjacent mines or factories that consume the deposit",
    HydroPowerPlant: "Hydro Power Plant",
    ElectricFishPond: "Electric Fish Pond",
    ElectricFishPondDesc: "Each working hydro power plant provides 20% capacity boost to all fish ponds on the map",
    AccountLimitedDescV2: "Your account fails to satisfy platform requirement",
    AccountLimitedActionV2: "Read FAQ on Limited Account",
    CropOutputx2: "Modern Fertilizer",
    CropOutputx2Desc: "Farmlands and greenhouses produce 2x crops but crop transport costs 2x fuel",
    MeatProductionx2: "Livestock Steroid",
    MeatProductionx2Desc:
        "Chicken farms, pig farms, cow farms, fish ponds and fodder factories have 2x capacity but uses 2x power",
    HydroFarming: "Hydro Farming",
    HydroFarmingDesc: "Each working hydro dam provides 20% capacity boost to all farmlands and greenhouses on the map",
    ExtraTradeQuota: "Extra Player Trade Quota",
    ExtraTradeQuotaDesc: "Initial player trade quota is 1% of your market cap - this will grant extra percentage",
    ProduceAllCrops: "Produce All Crops",
    ProduceAllCropsDesc: "Farmlands and greenhouses can produce all crops, including the ones that are not on the map",
    ResearchAgreement: "Research Agreement",
    ResearchAgreementDesc: "Filling each trade with an unique player gives 10 mins of research point production",
    NewsEffectx2V2: "Press Conference",
    NewsEffectx2DescV2: "All market news are 50% more effective",
    AutoSellCapacityMultiplierV2: "Extra Auto Sell Capacity",
    AutoSellCapacityMultiplierDescV2: "This will give extra auto sell capacity on top of your existing capacity",
    AutoSellCapacity: "Auto Sell Capacity",
    AutoSellCapacityDescV2:
        "Max amount of resources auto sell can handle per second, per resource, measured as the percentage of your total production of that resource",
    AutoSellCapacityExtraPercentageFromSwiss: "Extra Percentage from Swiss Upgrade and Boost: %{n}%",
    BaselineAutoSellCapacity: "Baseline auto sell capacity: %{amount}",
    AchievementAuckland100: "Hoiho",
    AchievementAuckland100Desc: "Earn 100 Swiss Money in Auckland in a single run",
    AchievementAuckland500: "Whio",
    AchievementAuckland500Desc: "Earn 500 Swiss Money in Auckland in a single run",
    AchievementAuckland1000: "Kiwi",
    AchievementAuckland1000Desc: "Earn 1000 Swiss Money in Auckland in a single run",
    ExternalManageYourSave: "Import And Export Your Save",
    ExternalManageYourSaveDesc:
        "Due to technical limitation, Importing and exporting your save must be done from the game's official website",
    MREPlant: "Meal, Ready-To-Eat Plant",
    PlayerTradeTaxCreditProduction: "Tax Credit: Production",
    PlayerTradeTaxCreditProductionDescV2:
        "This tax credit is based on the amount of %{res} you've produced since the last market update. You have produced %{produced} and you have traded %{used}",
    PlayerTradeTaxCreditMarketCap: "Tax Credit: Market Cap",
    PlayerTradeTaxCreditMarketCapDesc:
        "This tax credit is %{percentage} of your market cap, can be upgraded via Swiss Upgrade/Boost. Total credit amount is %{total} and you have used %{used}",
    PlayerTradeGrossTradeValue: "Gross Trade Value",
    PlayerTradeTaxableValue: "Taxable Value",
    PlayerTradeTaxRate: "Tax Rate",
    PlayerTradeTaxRateDesc:
        "Tax rate is based on price difference between your local price and this trade - the tax rate is progressive. 0% ~ 50%: 0.5% for every 1% difference; 50% ~ 75%: 1% for every 1% difference; 75% ~ 100%: 2% for every 1% difference",
    PlayerTradeTaxPayable: "Tax Payable",
    PlayerTradeTradeValueAfterTax: "Trade Value After Tax",
    PlayerTradeShowTaxCalculation: "Show Tax Calculation",
    PlayerTradeHideTaxCalculation: "Hide Tax Calculation",
    PlayerTradeMaxTaxCreditValue: "Set Amount to Match Tax Credit",
    WaterProductionx2: "Super Water Pump",
    WaterProductionx2Desc: "Water pumps produce 2x output but consumes 2x power",
    InputBufferTypeAuto: "Auto",
    InputBufferTypeStockpile: "Stockpile",
    InputBuffer: "Resource Input Buffer",
    InputBufferDesc:
        "The maximum cycles of input resource to keep in the storage before this building will no longer transport that resource. Auto means using prediction to keep a minimum buffer that allows continuous production. Stockpile means always transporting input resources regardless of the amount in the storage",
    InputCapacityOverride: "Input Capacity Override",
    InputCapacityOverrideDesc: "For each production cycle, transport %{percent} of the resources needed for production",
    PumpkinSpiceLatte: "Pumpkin Spice Latte",
    PumpkinPie: "Pumpkin Pie",
    QuantumComputerLab: "Quantum Computer Lab",
    QuantumComputer: "Quantum Computer",
    TVStudioPlus: "TV Studio+",
};
